import type { CardDef, CardId, CharacterId, Element, EnemyId, GoliathActionId, SkillDef, SkillId, StageId } from "./types";

// Prototype v2 (energy-card version) numbers. Change only with the designer's approval.
export const RULES_V2 = {
  openingHand: 5,
  drawPerTurn: 3,
  maxHand: 7,

  /** Faith and Guard carry over between turns up to these caps; Attack resets each turn. */
  maxFaith: 6,
  maxGuard: 6,
  /** David's passive "Against the Giant": while Faith ≥ this, David's attacks +giantBonus. */
  giantFaith: 3,
  giantBonus: 20,

  /** Victory when Goliath falls; the others flee (1 Sam 17:51). */
  archerDamage: 30,
  spear: 30,
  crush: 90,
  swing: 50,
  defyTargets: 2,

  healAmount: 50,
  ariseHp: 70,
  covShield: 30,
  /** The Serpent of Eden. Coil hits every ally. */
  fang: 60,
  fangShed: 80,
  coil: 40,
  temptFaith: 1,

  /** Story bonuses: a character fighting in their own Bible story. */
  /** Sling Stone away from Goliath: ordinary damage, no Stun. */
  slingStoneElsewhere: 80,
  /** Adam in Eden: Till the Ground +20, Keep the Garden Shield +30. */
  edenTillBonus: 20,
  edenKeepBonus: 30,
  /** Eve in Eden: Mother of All Living +20, and every ally's attacks on the Serpent +20 (Genesis 3:15). */
  edenMotherBonus: 20,
  edenSeedBonus: 20,

  /** Enemy cards played on the player's side. */
  shieldUpAmount: 50,

  /** Adam's Keep the Garden: Shield on himself. */
  keepShield: 50,
  /** Cain's Fruit of the Ground also gives Faith; his Mark strikes back at every enemy that hits him. */
  offeringFaith: 1,
  markRetaliate: 30,
  /** Abel's Firstlings of the Flock heals one ally; when he falls, Yet Speaketh shields every ally and gives Faith. */
  firstlingsHeal: 40,
  speakethShield: 30,
  speakethFaith: 1,
  /** Noah's Build the Ark shields every ally; his Rainbow Covenant (once per battle) heals every ally and lifts Shaken. */
  arkShield: 40,
  rainbowHeal: 50,
  /** Abraham's Look Toward Heaven gives Faith; The LORD Will Provide (once per battle) draws cards. */
  starsFaith: 2,
  provideDraw: 3,
  /** Isaac's Hundredfold Harvest hits harder with Abraham in the line-up; the Ram leaves a falling ally at this HP. */
  harvestBlessing: 20,
  ramHp: 10,
  /** Jacob's Wrestle Until Dawn costs him HP and wins the party Faith. */
  wrestleCost: 10,
  wrestleFaith: 1,
  /** Joseph's Storehouses heal and shield every ally; God Meant It for Good turns half the party's lost HP into damage. */
  granaryHeal: 30,
  granaryShield: 20,
  goodCap: 100,
  /** Moses' Hold Up His Hands: every ally's attacks this turn +20. */
  handsBonus: 20,
  /** Aaron's Blessing heals and shields one ally. */
  blessingHeal: 30,
  blessingShield: 30,
  /** Miriam's Song of the Sea gives Faith and lifts Shaken from everyone. */
  songFaith: 2,
  /** Moses at Sinai: The Ten Words shield every ally and give Faith. */
  tenWordsShield: 30,
  tenWordsFaith: 1,
  /** Rahab's Hide the Spies shields one ally. */
  hideShield: 40,
  /** Deborah's Up! This Is the Day gives Attack energy. */
  upTodayAttack: 2,
  /** Gideon's Sign of the Fleece gives Faith and draws a card. */
  fleeceFaith: 1,
  fleeceDraw: 1,
  /** Ruth's Gleaning draws cards. */
  gleanDraw: 2,
  /** Naomi's Counsel heals one ally (double for Ruth); Restorer of Life raises a fallen ally. */
  counselHeal: 30,
  restorerHp: 50,
  /** Boaz's Under His Wings shields one ally. */
  wingsShield: 60,
  /** Hannah's Silent Prayer gives Faith (more with Samuel beside her); her Song heals every ally. */
  prayerFaith: 1,
  prayerSamuelFaith: 2,
  hannahSongHeal: 40,
  /** Saul's Rash Offering gives Faith at once, but Saul is Shaken next turn. */
  rashFaith: 2,
  /** Abigail's Provision heals every ally; her Intercession softens every hit this turn. */
  provisionHeal: 20,
  intercedeBlock: 20,
  /** Solomon's Ask for Wisdom gives Faith and Attack; Fire from Heaven also heals every ally. */
  wisdomFaith: 1,
  wisdomAttack: 1,
  templeFireHeal: 30,
  /** Elijah's Fed by Ravens heals him and draws a card. */
  ravensHeal: 40,
  ravensDraw: 1,
  /** Elisha's Healing the Waters (double with Elijah beside him); Chariots of Fire shield every ally. */
  healWatersHeal: 20,
  chariotsShield: 50,
  /** Jonah comes back out of the fish with this HP, once per battle. */
  fishHp: 50,
  /** Esther's Fasting gives Faith at the cost of her HP. */
  fastingFaith: 2,
  fastingCost: 10,
  /** Nehemiah's wall: Shield to every ally, +10 per earlier course this battle, up to the cap. */
  wallShield: 20,
  wallStep: 10,
  wallCap: 50,
  /** Sword and Trowel also shields Nehemiah. */
  trowelShield: 20,
  /** Zechariah: Incense gives Faith and a small Shield to all; His Name Is John (from turn 3) heals all and gives Faith. */
  incenseFaith: 1,
  incenseShield: 10,
  johnTurn: 3,
  johnHeal: 40,
  johnFaith: 2,
  /** Mary's Handmaid gives Faith; the Magnificat takes a share of the leader's HP. */
  handmaidFaith: 1,
  magnificatShare: 0.25,
  /** Joseph of Nazareth's Carpenter's Hands shield and heal one ally (double for Mary). */
  carpenterShield: 30,
  carpenterHeal: 20,
  /** John the Baptist: the Axe hits wood enemies double; Baptism heals every ally (+1 Faith with Zechariah). */
  baptismHeal: 30,
  /** Jesus: Cleansing the Leper heals one ally; Gethsemane shields every ally and gives Faith; the Loaves feed everyone. */
  leperHeal: 50,
  gethsemaneShield: 40,
  gethsemaneFaith: 2,
  loavesHeal: 40,
  loavesDraw: 3,
  loavesFaith: 1,
  /** Jesus (UR) rises on the third day: two turns after the turn he falls, with full HP. */
  riseAfter: 2,
  /** Peter: the Great Catch draws cards and gives Attack; his attacks are stronger with Jesus beside him. */
  catchDraw: 2,
  catchAttack: 1,
  peterWithJesus: 20,
  /** Andrew's A Lad Here draws cards and gives Faith. */
  ladDraw: 2,
  ladFaith: 1,
  /** John the Apostle's Love One Another heals and shields every ally (double with Jesus beside him). */
  loveHeal: 20,
  loveShield: 20,
  /** Matthew: Leaving the Tax Booth turns Guard into Attack; the Feast heals every ally and draws a card. */
  taxBoothAttack: 2,
  feastHeal: 30,
  feastDraw: 1,
  /** James: Mending the Nets heals one ally; Boanerges hits harder with John; when he falls, every attack +10. */
  mendHeal: 30,
  boanergesWithJohn: 20,
  cupBonus: 10,
  /** Thomas: Reach Hither Thy Finger gives Faith and makes him believe. */
  fingerFaith: 1,
  /** Mary Magdalene: Spices heal one ally; I Have Seen the Lord raises a fallen ally (Jesus at once, in full). */
  spicesHeal: 30,
  seenHp: 60,
  /** Martha: Serving turns Attack into Guard; Thy Brother Shall Rise Again brings the next fallen ally back with this HP. */
  servingGuard: 2,
  riseAgainHp: 50,
  /** Zacchaeus: the Sycamore gives Faith; Restore Fourfold gives Attack and Faith. */
  sycamoreFaith: 1,
  fourfoldAttack: 2,
  fourfoldFaith: 2,
  /** Mary of Bethany: At His Feet gives Faith (+1 Guard with Martha); Spikenard heals and shields every ally. */
  feetFaith: 2,
  spikenardHeal: 30,
  spikenardShield: 30,
  /** Lazarus: Loose Him shields and steadies one ally; Many Believed gives Faith and heals everyone a little. */
  looseShield: 30,
  believedFaith: 1,
  believedHeal: 10,
  /** Stephen's Heavens Opened heals every ally and lifts Shaken. */
  heavensHeal: 40,
  /** Philip: Here Is Water heals and steadies one ally; Preaching in Samaria hits every enemy and gives Faith. */
  waterHeal: 30,
  samariaFaith: 1,
  /** Paul: the Armour of God shields and steadies every ally; the Sword of the Spirit gives Faith; weak, he is strong. */
  armourShield: 30,
  swordFaith: 1,
  strongWhenWeak: 20,
  /** Barnabas: Encouragement steadies everyone and gives Attack (and shields Paul); Sold His Field gives Faith once. */
  encourageAttack: 1,
  encouragePaulShield: 30,
  fieldFaith: 3,
  /** Silas: Hymns at Midnight steady everyone and give Faith (more with Paul). */
  hymnsFaith: 1,
  hymnsPaulFaith: 2,
  /** Timothy: Be an Example strengthens every attack this turn; Stir Up the Gift hits harder with Paul. */
  exampleBonus: 10,
  stirWithPaul: 20,
  /** Lydia: Purple Cloth shields one ally and gives Faith; Abide in My House heals everyone (+1 Faith with Paul or Silas). */
  purpleShield: 30,
  purpleFaith: 1,
  abideHeal: 30,
  /** Priscilla: Tentmaking shields every ally; Expounding the Way strengthens one ally's attacks this turn. */
  tentShield: 20,
  expoundBonus: 30,
  /** Eli: Go in Peace heals one ally and gives Faith (double for Hannah); Speak, Lord lets an ally act again. */
  peaceHeal: 20,
  peaceFaith: 1,
  /** Aquila shields himself when he steps in front, with Priscilla beside him. */
  aquilaShield: 20,
  /** Dorcas: Garments heal and shield every ally a little; Almsdeeds heals one ally. */
  garmentHeal: 10,
  garmentShield: 10,
  almsHeal: 30,
  /** Cornelius' Prayers and Alms give Faith (+1 Attack with Peter in the line-up). */
  memorialFaith: 1,
  /** Apollos: Mighty in the Scriptures hits harder with Priscilla or Aquila; Watered heals every ally. */
  scripturesWithTeachers: 20,
  wateredHeal: 20,
  /** Phoebe: Succourer of Many heals one ally and gives Guard; Bearer of the Letter gives Faith and draws (more with Paul). */
  succourHeal: 30,
  letterFaith: 1,
  letterDraw: 1,
  /** Luke: the Beloved Physician heals one ally (double for Paul); In Order draws cards; with Paul he is shielded each turn. */
  physicianHeal: 40,
  orderDraw: 2,
  lukeShield: 10,
  /** John Mark: Departing gives Faith but he is Shaken next turn; Profitable hits harder with Barnabas or Paul. */
  departFaith: 2,
  profitableWith: 20,
  /** Titus: Set in Order gives a Guard and an Attack; Earnest Care shields every ally (more with Paul). */
  earnestShield: 20,
  earnestPaulShield: 30,
  /** Philemon: Refreshed heals and steadies every ally; Receive Him raises a fallen ally (more with Paul). */
  refreshHeal: 20,
  receiveHp: 50,
  receivePaulHp: 80,
  /** Onesimus' Brother Beloved gives Faith. */
  brotherFaith: 1,
  /** Nicodemus: By Night draws (2 with Jesus) and gives Faith. */
  nightDraw: 1,
  nightFaith: 1,
  /** The Samaritan woman: Living Water heals every ally (double with Jesus). */
  livingHeal: 20,
  /** Simeon: Nunc Dimittis heals and shields everyone, then Simeon departs in peace. */
  nuncHeal: 40,
  nuncShield: 20,
  /** Anna: Night and Day shields everyone a little and gives Faith; Gave Thanks gives Faith (2 with Simeon). */
  annaShield: 10,
  /** The boy with the loaves: the Basket gives Faith (and heals everyone with Jesus). */
  basketFaith: 3,
  /** Elizabeth: the babe Leaped heals everyone (+1 Faith with Mary or John the Baptist); Blessed Among Women heals and shields an ally (double for Mary). */
  leapHeal: 20,
  blessedHeal: 40,
  blessedShield: 20,
  /** Mordecai: Would Not Bow shields him and steadies every ally; For Such a Time gives Faith (2 with Esther). */
  bowShield: 30,
  /** Sarah: Laughter heals everyone and gives Faith (2 with Abraham or Isaac); Too Hard restores an ally to full HP once. */
  laughHeal: 20,
  /** Rebekah: Drink, My Lord heals an ally; Water for the Camels heals and shields everyone (+1 Faith with Isaac). */
  drinkHeal: 30,
  camelsHeal: 20,
  camelsShield: 10,
  /** Rachel: Keeping the Sheep shields everyone (double with Jacob or Joseph); A Few Days gives Faith (2 with Jacob). */
  sheepShield: 10,
  /** Barak: If Thou Wilt Go gives Attack (2 with Deborah); Down from Tabor strikes (+20 with Deborah). */
  thouGoAttack: 1,
  /** Jael: the Tent Peg strikes hard (+30 on a foe at half HP or less). */
  pegFinish: 30,
  /** Joseph of Arimathea: Fine Linen heals and shields an ally; his new tomb lets Jesus (UR) rise a turn sooner. */
  linenHeal: 30,
  linenShield: 20,
  /** Ananias: Brother Saul heals an ally (double for Paul); the Scales Fell steadies and shields everyone (+1 Faith with Paul). */
  brotherHeal: 30,
  scalesShield: 10,
  /** Job: the LORD Gave shields him (+1 Faith when at half HP or less); Turned His Captivity restores him twice over, once. */
  jobShield: 30,
  captivityShieldMax: 60,
  /** Enoch: Walked with God gives Faith and shields him; when God takes him, every ally heals and the team gains Faith. */
  walkShield: 20,
  takenHeal: 30,
  takenFaith: 2,
  /** Melchizedek: Bread and Wine heals everyone (+1 Faith with Abraham); Tithes of All gives Faith (3 with Abraham). */
  breadHeal: 20,
  titheFaith: 2,
  /** Caleb: Go Up at Once gives Attack (2 with Joshua) and steadies everyone; Give Me This Mountain hits harder while he is at full HP. */
  goUpAttack: 1,
  stillStrong: 20,
  /** Jeremiah: the Almond Rod draws a card and gives Faith; Fire in My Bones burns hotter when he is at half HP or less. */
  bonesBonus: 20,
  /** Ezekiel: the Watchman shields everyone and gives Faith; the Dry Bones Live raises every fallen ally, once. */
  watchmanShield: 10,
  dryBonesHp: 30,
  /** Ezra: Prepared His Heart draws cards; Read in the Book gives Faith (3 with Nehemiah) and steadies everyone. */
  ezraDraw: 2,
  lawFaith: 2,
  /** Nathan: Thou Art the Man strikes the leader harder; Thy House Established shields everyone (David and Solomon most). */
  manBonus: 20,
  houseShield: 10,
  houseKingShield: 30,
  /** Hezekiah: Fifteen Years heals him (double with Isaiah); Spread the Letter strikes every enemy once. */
  fifteenHeal: 50,
  /** The Magi: His Star gives Faith (2 with Mary or Jesus); the Three Gifts give Attack, heal and shield everyone, once. */
  giftAttack: 2,
  giftHeal: 20,
  giftShield: 20,
  /** The shepherds: Good Tidings steadies everyone; Glory to God heals and shields everyone. */
  gloryHeal: 20,
  gloryShield: 10,
  /** Bartimaeus: Son of David gives Faith (2 with Jesus); Casting Away His Garment strikes (+20 with Jesus). */
  garmentWithJesus: 20,
  /** The centurion: Speak the Word heals another ally from afar (more with Jesus); Under Authority sends an ally to act again. */
  wordHeal: 40,
  wordHealJesus: 60,
  /** Jairus: Only Believe gives Faith (2 with Jesus); Talitha Cumi raises a fallen ally once (full HP with Jesus). */
  talithaHp: 50,
  /** Simon of Cyrene: Bear His Cross takes an ally's blows this turn and shields Simon; Out of the Country heals him. */
  crossShield: 20,
  countryHeal: 30,
  /** The penitent thief: Remember Me gives Faith (2 with Jesus); To Day in Paradise heals everyone and gives Faith, then he departs. */
  paradiseHeal: 40,
  paradiseFaith: 2,
  /** James the Lord's brother: Swift to Hear shields everyone (+1 Faith with Peter or Paul); Faith with Works grows with the Faith held. */
  hearShield: 10,
  worksPerFaith: 10,
  worksMax: 30,
  /** The criminal who mocked: Railed On hits hard, but the railing costs him HP. */
  railCost: 20,
  /** Jesus on the cross: It Is Finished strikes every enemy and heals every ally, then he gives up the ghost. */
  finishedHeal: 40,
  /** The four friends: Through the Roof heals another ally (double with Jesus); Their Faith gives Faith (3 with Jesus). */
  roofHeal: 30,
  theirFaith: 2,
  /** The good Samaritan: Oil and Wine heals another ally; Two Pence heals an ally at the start of each of the next 2 turns. */
  oilHeal: 40,
  innHeal: 20,
  innTurns: 2,
  /** Pharaoh: a Hardened Heart shields him; More Bricks gives Attack at the cost of every other ally's HP. */
  hardShield: 30,
  bricksAttack: 2,
  bricksCost: 10,
  /** The Egyptian charioteer: Pursued strikes (+20 with Pharaoh); Chosen Chariots give Attack and shield him. */
  chariotShield: 10,
  /** Jezebel: Royal Command gives Attack and shields her; Sealed Letters reach any enemy, even behind the shield bearer. */
  queenShield: 20,
  /** The prophet of Baal: Call on Baal grows louder each turn; Cut Themselves gives Attack at the cost of his HP. */
  baalPerTurn: 10,
  baalMax: 40,
  cutCost: 20,
  cutAttack: 2,
  /** Haman: the King's Ring gives Attack; the Decree strikes every enemy, but with Esther or Mordecai it comes back on him. */
  ringAttack: 2,
  gallowsCost: 30,
  /** Nebuchadnezzar: Seven Times Hotter strikes every enemy; Praise the King of Heaven heals everyone and gives Faith, once. */
  heavenHeal: 30,
  heavenFaith: 2,
  basketHeal: 30,
  /** Judas: Thirty Pieces of Silver give Faith at an ally's cost; the Money Bag strikes and gives Faith. */
  silverFaith: 3,
  silverCost: 20,

  /** Eve's Mother of All Living: heals every ally. */
  motherHeal: 40,

  /** Elements are reserved for multi-stage play: switched off, so damage is unaffected for now. */
  elements: {
    enabled: true,
    /** Attacker's element beats the defender's. */
    strong: 1.5,
    /** Defender's element beats the attacker's (water/fire/wood cycle). */
    weak: 0.75,
  },

  /** Delay between Goliath's action and the next turn in the UI (ms). */
  stepDelay: 800,
} as const;

/**
 * Which elements each element beats: the five phases' overcoming cycle (wood → earth → water → fire → metal → wood),
 * plus light and dark countering each other. Every element beats one and is beaten by one; light and dark are
 * neutral to the five phases.
 */
export const ELEMENT_BEATS: Record<Element, Element[]> = {
  wood: ["earth"],
  earth: ["water"],
  water: ["fire"],
  fire: ["metal"],
  metal: ["wood"],
  light: ["dark"],
  dark: ["light"],
};

/** Adam is earth (formed from the dust, Genesis 2:7); Goliath is metal (bronze armour, 1 Samuel 17:5-7). */
export const CHARACTER_ELEMENT: Record<CharacterId, Element> = {
  david: "light",
  samuel: "water",
  jonathan: "fire",
  adam: "earth",
  cain: "earth",
  abel: "light",
  noah: "water",
  abraham: "metal",
  isaac: "wood",
  jacob: "earth",
  joseph: "metal",
  moses: "fire",
  aaron: "light",
  miriam: "water",
  mosesSinai: "light",
  joshua: "metal",
  rahab: "fire",
  deborah: "wood",
  gideon: "fire",
  samson: "earth",
  ruth: "wood",
  naomi: "water",
  boaz: "metal",
  hannah: "water",
  saul: "metal",
  abigail: "light",
  solomon: "fire",
  elijah: "fire",
  elisha: "water",
  jonah: "water",
  isaiah: "light",
  esther: "metal",
  daniel: "earth",
  nehemiah: "earth",
  zechariah: "light",
  mary: "wood",
  josephNaz: "wood",
  johnBaptist: "water",
  jesus: "light",
  jesusUR: "light",
  peter: "earth",
  andrew: "water",
  johnApostle: "fire",
  matthew: "metal",
  jamesZeb: "fire",
  thomas: "wood",
  maryMagdalene: "wood",
  martha: "earth",
  zacchaeus: "metal",
  maryBethany: "wood",
  lazarus: "earth",
  stephen: "light",
  philip: "water",
  paul: "metal",
  barnabas: "earth",
  silas: "metal",
  timothy: "fire",
  lydia: "water",
  priscilla: "wood",
  eli: "fire",
  aquila: "earth",
  dorcas: "wood",
  cornelius: "metal",
  apollos: "water",
  phoebe: "water",
  luke: "water",
  johnMark: "wood",
  titus: "earth",
  philemon: "wood",
  onesimus: "wood",
  nicodemus: "water",
  samaritan: "water",
  simeon: "light",
  anna: "light",
  elizabeth: "wood",
  mordecai: "metal",
  sarah: "earth",
  rebekah: "water",
  rachel: "wood",
  barak: "earth",
  jael: "metal",
  josephArimathea: "light",
  ananias: "water",
  threeFriends: "fire",
  job: "earth",
  enoch: "light",
  melchizedek: "light",
  caleb: "earth",
  jeremiah: "fire",
  ezekiel: "wood",
  ezra: "water",
  nathan: "metal",
  hezekiah: "water",
  josiah: "fire",
  magi: "light",
  shepherds: "wood",
  bartimaeus: "light",
  centurion: "metal",
  jairus: "earth",
  simonCyrene: "earth",
  thief: "light",
  jamesJust: "earth",
  mockingThief: "dark",
  jesusCross: "light",
  widow: "earth",
  fisherman: "water",
  fourFriends: "earth",
  goodSamaritan: "wood",
  pharaoh: "metal",
  charioteer: "metal",
  jezebel: "dark",
  baalProphet: "dark",
  haman: "dark",
  delilah: "dark",
  nebuchadnezzar: "fire",
  loavesBoy: "earth",
  judas: "dark",
  philipApostle: "earth",
  nathanael: "wood",
  jamesAlph: "earth",
  thaddaeus: "water",
  simonZealot: "fire",
  matthias: "light",
  eve: "wood",
  archerP: "fire",
  bearerP: "wood",
  goliathP: "metal",
  serpentP: "dark",
};
export const ENEMY_ELEMENT: Record<EnemyId, Element> = { bearer: "wood", goliath: "metal", archer: "fire", serpent: "dark" };

/** Cards that show the same person: a line-up holds only one of them. */
export const PERSON: Partial<Record<CharacterId, CharacterId>> = { mosesSinai: "moses", jesusUR: "jesus", jesusCross: "jesus" };

/** The twelve apostles (Matthew 10:2-4), for One of the Twelve. */
export const APOSTLES: ReadonlySet<CharacterId> = new Set(["peter", "andrew", "jamesZeb", "johnApostle", "philipApostle", "nathanael", "thomas", "matthew", "jamesAlph", "thaddaeus", "simonZealot", "judas", "matthias"]);

/** Cards that never fall: never targeted, never hurt, and not counted when deciding defeat. */
export const NEVER_FALLS: ReadonlySet<CharacterId> = new Set(["jesus"]);
export const personOf = (id: CharacterId): CharacterId => PERSON[id] ?? id;

/** Every playable character, in display order. */
export const PARTY_ORDER: CharacterId[] = ["david", "samuel", "jonathan", "adam", "eve", "cain", "abel", "noah", "abraham", "isaac", "jacob", "joseph", "moses", "aaron", "miriam", "mosesSinai", "joshua", "rahab", "deborah", "gideon", "samson", "ruth", "naomi", "boaz", "hannah", "saul", "abigail", "solomon", "elijah", "elisha", "jonah", "isaiah", "esther", "daniel", "nehemiah", "zechariah", "mary", "josephNaz", "johnBaptist", "jesus", "jesusUR", "peter", "andrew", "johnApostle", "matthew", "jamesZeb", "thomas", "maryMagdalene", "martha", "zacchaeus", "maryBethany", "lazarus", "stephen", "philip", "paul", "barnabas", "silas", "timothy", "lydia", "priscilla", "eli", "aquila", "dorcas", "cornelius", "apollos", "phoebe", "luke", "johnMark", "titus", "philemon", "onesimus", "nicodemus", "samaritan", "simeon", "anna", "loavesBoy", "judas", "philipApostle", "nathanael", "jamesAlph", "thaddaeus", "simonZealot", "matthias", "elizabeth", "mordecai", "sarah", "rebekah", "rachel", "barak", "jael", "josephArimathea", "ananias", "threeFriends", "job", "enoch", "melchizedek", "caleb", "jeremiah", "ezekiel", "ezra", "nathan", "hezekiah", "josiah", "magi", "shepherds", "bartimaeus", "centurion", "jairus", "simonCyrene", "thief", "jamesJust", "jesusCross", "widow", "fisherman", "fourFriends", "goodSamaritan", "mockingThief", "pharaoh", "charioteer", "jezebel", "baalProphet", "haman", "delilah", "nebuchadnezzar", "goliathP", "serpentP", "bearerP", "archerP"];
/** Who fights when no line-up is chosen (the v2 battle). */
export const DEFAULT_LINEUP: CharacterId[] = ["david", "samuel", "jonathan"];

export const ENEMY_ORDER: EnemyId[] = ["bearer", "goliath", "archer", "serpent"];

/** Each character's own Bible story: fighting in that stage turns on their story bonus. */
export const STORY: Partial<Record<CharacterId, StageId>> = { david: "goliath", adam: "eden", eve: "eden" };

/** Who fights in each stage, and the boss. */
export const STAGE_ENEMIES: Record<StageId, EnemyId[]> = { goliath: ["bearer", "goliath", "archer"], eden: ["serpent"] };
export const STAGE_BOSS: Record<StageId, EnemyId> = { goliath: "goliath", eden: "serpent" };

/** HP and damage use Pokémon-TCG-style numbers (steps of 10). */
export const ENEMY_HP: Record<EnemyId, number> = { bearer: 60, goliath: 220, archer: 40, serpent: 250 };

export const MAX_HP: Record<CharacterId, number> = { david: 120, samuel: 100, jonathan: 140, adam: 130, eve: 120, cain: 120, abel: 120, noah: 140, abraham: 130, isaac: 100, jacob: 130, joseph: 120, moses: 130, aaron: 130, miriam: 100, mosesSinai: 130, joshua: 140, rahab: 100, deborah: 110, gideon: 120, samson: 150, ruth: 120, naomi: 90, boaz: 130, hannah: 100, saul: 150, abigail: 100, solomon: 130, elijah: 120, elisha: 120, jonah: 110, isaiah: 110, esther: 110, daniel: 130, nehemiah: 130, zechariah: 100, mary: 110, josephNaz: 130, johnBaptist: 120, jesus: 100, jesusUR: 150, peter: 140, andrew: 110, johnApostle: 110, matthew: 110, jamesZeb: 120, thomas: 110, maryMagdalene: 110, martha: 120, zacchaeus: 90, maryBethany: 100, lazarus: 120, stephen: 110, philip: 110, paul: 130, barnabas: 120, silas: 110, timothy: 100, lydia: 110, priscilla: 110, eli: 90, aquila: 110, dorcas: 100, cornelius: 140, apollos: 110, phoebe: 100, luke: 110, johnMark: 100, titus: 120, philemon: 110, onesimus: 90, nicodemus: 110, samaritan: 100, simeon: 100, anna: 90, loavesBoy: 80, judas: 100, philipApostle: 110, nathanael: 110, jamesAlph: 120, thaddaeus: 110, simonZealot: 120, matthias: 110, elizabeth: 100, mordecai: 130, sarah: 110, rebekah: 110, rachel: 100, barak: 130, jael: 100, josephArimathea: 110, ananias: 100, threeFriends: 150, job: 150, enoch: 110, melchizedek: 120, caleb: 140, jeremiah: 110, ezekiel: 120, ezra: 110, nathan: 110, hezekiah: 120, josiah: 120, magi: 150, shepherds: 140, bartimaeus: 100, centurion: 130, jairus: 110, simonCyrene: 140, thief: 80, jamesJust: 120, mockingThief: 90, jesusCross: 120, widow: 80, fisherman: 100, fourFriends: 160, goodSamaritan: 120, pharaoh: 140, charioteer: 110, jezebel: 110, baalProphet: 100, haman: 120, delilah: 100, nebuchadnezzar: 140, archerP: 70, bearerP: 110, goliathP: 150, serpentP: 100 };

export const SKILLS: Record<SkillId, SkillDef> = {
  sling: { id: "sling", owner: "david", kind: "attack", cost: 1, damage: 30 },
  slingStone: { id: "slingStone", owner: "david", kind: "faith", cost: 3, damage: 140 },
  rebuke: { id: "rebuke", owner: "samuel", kind: "attack", cost: 1, damage: 20 },
  heal: { id: "heal", owner: "samuel", kind: "guard", cost: 1 },
  arise: { id: "arise", owner: "samuel", kind: "guard", cost: 2 },
  sword: { id: "sword", owner: "jonathan", kind: "attack", cost: 1, damage: 30 },
  covshield: { id: "covshield", owner: "jonathan", kind: "guard", cost: 1 },
  till: { id: "till", owner: "adam", kind: "attack", cost: 1, damage: 30 },
  keep: { id: "keep", owner: "adam", kind: "guard", cost: 1 },
  mother: { id: "mother", owner: "eve", kind: "guard", cost: 1 },
  helper: { id: "helper", owner: "eve", kind: "guard", cost: 1 },
  offering: { id: "offering", owner: "cain", kind: "attack", cost: 1, damage: 20 },
  mark: { id: "mark", owner: "cain", kind: "guard", cost: 2 },
  firstlings: { id: "firstlings", owner: "abel", kind: "guard", cost: 1 },
  faithOffering: { id: "faithOffering", owner: "abel", kind: "attack", cost: 1, damage: 20 },
  ark: { id: "ark", owner: "noah", kind: "guard", cost: 2 },
  rainbow: { id: "rainbow", owner: "noah", kind: "guard", cost: 3 },
  stars: { id: "stars", owner: "abraham", kind: "guard", cost: 1 },
  provide: { id: "provide", owner: "abraham", kind: "faith", cost: 2 },
  harvest: { id: "harvest", owner: "isaac", kind: "attack", cost: 1, damage: 20 },
  ram: { id: "ram", owner: "isaac", kind: "guard", cost: 2 },
  wrestle: { id: "wrestle", owner: "jacob", kind: "attack", cost: 2, damage: 40 },
  ladder: { id: "ladder", owner: "jacob", kind: "faith", cost: 3 },
  granary: { id: "granary", owner: "joseph", kind: "guard", cost: 2 },
  meantForGood: { id: "meantForGood", owner: "joseph", kind: "faith", cost: 2 },
  sea: { id: "sea", owner: "moses", kind: "faith", cost: 3, damage: 60 },
  handsUp: { id: "handsUp", owner: "moses", kind: "guard", cost: 2 },
  blessing: { id: "blessing", owner: "aaron", kind: "guard", cost: 1 },
  breastplate: { id: "breastplate", owner: "aaron", kind: "guard", cost: 2 },
  timbrel: { id: "timbrel", owner: "miriam", kind: "attack", cost: 1, damage: 10 },
  song: { id: "song", owner: "miriam", kind: "guard", cost: 2 },
  tenWords: { id: "tenWords", owner: "mosesSinai", kind: "guard", cost: 2 },
  faceShone: { id: "faceShone", owner: "mosesSinai", kind: "faith", cost: 3 },
  courage: { id: "courage", owner: "joshua", kind: "attack", cost: 1, damage: 30 },
  jericho: { id: "jericho", owner: "joshua", kind: "faith", cost: 3, damage: 40 },
  hideSpies: { id: "hideSpies", owner: "rahab", kind: "guard", cost: 1 },
  scarletCord: { id: "scarletCord", owner: "rahab", kind: "guard", cost: 3 },
  upToday: { id: "upToday", owner: "deborah", kind: "attack", cost: 1 },
  starsFought: { id: "starsFought", owner: "deborah", kind: "faith", cost: 3, damage: 60 },
  fleece: { id: "fleece", owner: "gideon", kind: "guard", cost: 1 },
  torches: { id: "torches", owner: "gideon", kind: "faith", cost: 3, damage: 30 },
  jawbone: { id: "jawbone", owner: "samson", kind: "attack", cost: 2, damage: 30 },
  pillars: { id: "pillars", owner: "samson", kind: "faith", cost: 3, damage: 100 },
  glean: { id: "glean", owner: "ruth", kind: "guard", cost: 1 },
  whither: { id: "whither", owner: "ruth", kind: "guard", cost: 1 },
  counsel: { id: "counsel", owner: "naomi", kind: "guard", cost: 1 },
  restorer: { id: "restorer", owner: "naomi", kind: "guard", cost: 2 },
  wings: { id: "wings", owner: "boaz", kind: "guard", cost: 2 },
  redeemer: { id: "redeemer", owner: "boaz", kind: "guard", cost: 2 },
  prayer: { id: "prayer", owner: "hannah", kind: "guard", cost: 1 },
  hannahSong: { id: "hannahSong", owner: "hannah", kind: "faith", cost: 3, damage: 40 },
  javelin: { id: "javelin", owner: "saul", kind: "attack", cost: 1, damage: 30 },
  rashOffering: { id: "rashOffering", owner: "saul", kind: "guard", cost: 1 },
  provision: { id: "provision", owner: "abigail", kind: "guard", cost: 1 },
  intercede: { id: "intercede", owner: "abigail", kind: "guard", cost: 2 },
  wisdom: { id: "wisdom", owner: "solomon", kind: "guard", cost: 1 },
  templeFire: { id: "templeFire", owner: "solomon", kind: "faith", cost: 3, damage: 50 },
  ravens: { id: "ravens", owner: "elijah", kind: "guard", cost: 1 },
  carmel: { id: "carmel", owner: "elijah", kind: "faith", cost: 3, damage: 80 },
  healWaters: { id: "healWaters", owner: "elisha", kind: "guard", cost: 1 },
  chariots: { id: "chariots", owner: "elisha", kind: "faith", cost: 2 },
  castIntoSea: { id: "castIntoSea", owner: "jonah", kind: "guard", cost: 1 },
  nineveh: { id: "nineveh", owner: "jonah", kind: "attack", cost: 2, damage: 20 },
  sendMe: { id: "sendMe", owner: "isaiah", kind: "attack", cost: 1, damage: 30 },
  greatLight: { id: "greatLight", owner: "isaiah", kind: "faith", cost: 3, damage: 60 },
  fasting: { id: "fasting", owner: "esther", kind: "guard", cost: 1 },
  contrary: { id: "contrary", owner: "esther", kind: "faith", cost: 3 },
  stoneCut: { id: "stoneCut", owner: "daniel", kind: "attack", cost: 2, damage: 50 },
  lionsDen: { id: "lionsDen", owner: "daniel", kind: "faith", cost: 2 },
  buildWall: { id: "buildWall", owner: "nehemiah", kind: "guard", cost: 1 },
  swordAndTrowel: { id: "swordAndTrowel", owner: "nehemiah", kind: "attack", cost: 1, damage: 20 },
  incense: { id: "incense", owner: "zechariah", kind: "guard", cost: 1 },
  nameIsJohn: { id: "nameIsJohn", owner: "zechariah", kind: "guard", cost: 2 },
  handmaid: { id: "handmaid", owner: "mary", kind: "guard", cost: 1 },
  magnificat: { id: "magnificat", owner: "mary", kind: "faith", cost: 3 },
  carpenter: { id: "carpenter", owner: "josephNaz", kind: "guard", cost: 1 },
  dreamWarning: { id: "dreamWarning", owner: "josephNaz", kind: "faith", cost: 2 },
  axe: { id: "axe", owner: "johnBaptist", kind: "attack", cost: 2, damage: 40 },
  baptism: { id: "baptism", owner: "johnBaptist", kind: "guard", cost: 2 },
  leper: { id: "leper", owner: "jesus", kind: "guard", cost: 1 },
  gethsemane: { id: "gethsemane", owner: "jesus", kind: "guard", cost: 2 },
  walkOnWater: { id: "walkOnWater", owner: "jesusUR", kind: "faith", cost: 2 },
  loaves: { id: "loaves", owner: "jesusUR", kind: "faith", cost: 3 },
  greatCatch: { id: "greatCatch", owner: "peter", kind: "guard", cost: 1 },
  drawSword: { id: "drawSword", owner: "peter", kind: "attack", cost: 2, damage: 50 },
  comeAndSee: { id: "comeAndSee", owner: "andrew", kind: "guard", cost: 2 },
  aLadHere: { id: "aLadHere", owner: "andrew", kind: "guard", cost: 1 },
  thunder: { id: "thunder", owner: "johnApostle", kind: "attack", cost: 1, damage: 30 },
  loveOneAnother: { id: "loveOneAnother", owner: "johnApostle", kind: "guard", cost: 2 },
  taxBooth: { id: "taxBooth", owner: "matthew", kind: "guard", cost: 1 },
  feast: { id: "feast", owner: "matthew", kind: "guard", cost: 2 },
  mendNets: { id: "mendNets", owner: "jamesZeb", kind: "guard", cost: 1 },
  boanerges: { id: "boanerges", owner: "jamesZeb", kind: "attack", cost: 1, damage: 30 },
  reachFinger: { id: "reachFinger", owner: "thomas", kind: "guard", cost: 1 },
  myLord: { id: "myLord", owner: "thomas", kind: "faith", cost: 2, damage: 50 },
  spices: { id: "spices", owner: "maryMagdalene", kind: "guard", cost: 1 },
  seenTheLord: { id: "seenTheLord", owner: "maryMagdalene", kind: "faith", cost: 2 },
  serving: { id: "serving", owner: "martha", kind: "attack", cost: 1 },
  riseAgain: { id: "riseAgain", owner: "martha", kind: "faith", cost: 2 },
  sycamore: { id: "sycamore", owner: "zacchaeus", kind: "guard", cost: 1 },
  fourfold: { id: "fourfold", owner: "zacchaeus", kind: "guard", cost: 1 },
  atHisFeet: { id: "atHisFeet", owner: "maryBethany", kind: "guard", cost: 1 },
  spikenard: { id: "spikenard", owner: "maryBethany", kind: "faith", cost: 2 },
  looseHim: { id: "looseHim", owner: "lazarus", kind: "guard", cost: 1 },
  manyBelieved: { id: "manyBelieved", owner: "lazarus", kind: "guard", cost: 1 },
  gracePower: { id: "gracePower", owner: "stephen", kind: "attack", cost: 1, damage: 30 },
  heavensOpened: { id: "heavensOpened", owner: "stephen", kind: "faith", cost: 2 },
  hereIsWater: { id: "hereIsWater", owner: "philip", kind: "guard", cost: 1 },
  samaria: { id: "samaria", owner: "philip", kind: "attack", cost: 2, damage: 20 },
  armourOfGod: { id: "armourOfGod", owner: "paul", kind: "guard", cost: 2 },
  swordOfSpirit: { id: "swordOfSpirit", owner: "paul", kind: "attack", cost: 2, damage: 50 },
  encourage: { id: "encourage", owner: "barnabas", kind: "guard", cost: 1 },
  soldField: { id: "soldField", owner: "barnabas", kind: "guard", cost: 1 },
  midnightHymns: { id: "midnightHymns", owner: "silas", kind: "guard", cost: 1 },
  prisonOpened: { id: "prisonOpened", owner: "silas", kind: "faith", cost: 2, damage: 30 },
  example: { id: "example", owner: "timothy", kind: "guard", cost: 1 },
  stirUpGift: { id: "stirUpGift", owner: "timothy", kind: "attack", cost: 1, damage: 30 },
  purpleCloth: { id: "purpleCloth", owner: "lydia", kind: "guard", cost: 1 },
  abideHouse: { id: "abideHouse", owner: "lydia", kind: "guard", cost: 2 },
  tentmaking: { id: "tentmaking", owner: "priscilla", kind: "guard", cost: 1 },
  expound: { id: "expound", owner: "priscilla", kind: "guard", cost: 1 },
  goInPeace: { id: "goInPeace", owner: "eli", kind: "guard", cost: 1 },
  speakLord: { id: "speakLord", owner: "eli", kind: "guard", cost: 2 },
  tentRope: { id: "tentRope", owner: "aquila", kind: "attack", cost: 1, damage: 20 },
  layDownNeck: { id: "layDownNeck", owner: "aquila", kind: "guard", cost: 1 },
  garments: { id: "garments", owner: "dorcas", kind: "guard", cost: 1 },
  almsdeeds: { id: "almsdeeds", owner: "dorcas", kind: "guard", cost: 1 },
  centurionCommand: { id: "centurionCommand", owner: "cornelius", kind: "attack", cost: 2, damage: 40 },
  prayersAlms: { id: "prayersAlms", owner: "cornelius", kind: "guard", cost: 1 },
  mightyScriptures: { id: "mightyScriptures", owner: "apollos", kind: "attack", cost: 1, damage: 30 },
  watered: { id: "watered", owner: "apollos", kind: "guard", cost: 1 },
  succourer: { id: "succourer", owner: "phoebe", kind: "guard", cost: 1 },
  bearLetter: { id: "bearLetter", owner: "phoebe", kind: "guard", cost: 1 },
  physician: { id: "physician", owner: "luke", kind: "guard", cost: 1 },
  inOrder: { id: "inOrder", owner: "luke", kind: "guard", cost: 1 },
  departed: { id: "departed", owner: "johnMark", kind: "guard", cost: 1 },
  profitable: { id: "profitable", owner: "johnMark", kind: "attack", cost: 1, damage: 20 },
  setInOrder: { id: "setInOrder", owner: "titus", kind: "faith", cost: 1 },
  earnestCare: { id: "earnestCare", owner: "titus", kind: "guard", cost: 2 },
  refreshed: { id: "refreshed", owner: "philemon", kind: "guard", cost: 1 },
  receiveHim: { id: "receiveHim", owner: "philemon", kind: "guard", cost: 2 },
  nowProfitable: { id: "nowProfitable", owner: "onesimus", kind: "attack", cost: 1, damage: 20 },
  belovedBrother: { id: "belovedBrother", owner: "onesimus", kind: "guard", cost: 1 },
  byNight: { id: "byNight", owner: "nicodemus", kind: "guard", cost: 1 },
  bornAgain: { id: "bornAgain", owner: "nicodemus", kind: "faith", cost: 2 },
  livingWater: { id: "livingWater", owner: "samaritan", kind: "guard", cost: 1 },
  comeSee: { id: "comeSee", owner: "samaritan", kind: "guard", cost: 1 },
  waiting: { id: "waiting", owner: "simeon", kind: "guard", cost: 1 },
  nuncDimittis: { id: "nuncDimittis", owner: "simeon", kind: "faith", cost: 2 },
  nightAndDay: { id: "nightAndDay", owner: "anna", kind: "guard", cost: 1 },
  gaveThanks: { id: "gaveThanks", owner: "anna", kind: "guard", cost: 1 },
  giveBasket: { id: "giveBasket", owner: "loavesBoy", kind: "guard", cost: 1 },
  pebble: { id: "pebble", owner: "loavesBoy", kind: "attack", cost: 1, damage: 10 },
  thirtySilver: { id: "thirtySilver", owner: "judas", kind: "guard", cost: 1 },
  moneyBag: { id: "moneyBag", owner: "judas", kind: "attack", cost: 1, damage: 20 },
  philipComeSee: { id: "philipComeSee", owner: "philipApostle", kind: "guard", cost: 1 },
  twoHundredPence: { id: "twoHundredPence", owner: "philipApostle", kind: "attack", cost: 1, damage: 30 },
  figTree: { id: "figTree", owner: "nathanael", kind: "guard", cost: 1 },
  noGuile: { id: "noGuile", owner: "nathanael", kind: "attack", cost: 1, damage: 30 },
  quietFaith: { id: "quietFaith", owner: "jamesAlph", kind: "guard", cost: 1 },
  oneOfTwelve: { id: "oneOfTwelve", owner: "jamesAlph", kind: "attack", cost: 1, damage: 20 },
  aQuestion: { id: "aQuestion", owner: "thaddaeus", kind: "guard", cost: 1 },
  contendFaith: { id: "contendFaith", owner: "thaddaeus", kind: "attack", cost: 1, damage: 30 },
  zeal: { id: "zeal", owner: "simonZealot", kind: "attack", cost: 1, damage: 30 },
  swordDown: { id: "swordDown", owner: "simonZealot", kind: "guard", cost: 1 },
  lotFell: { id: "lotFell", owner: "matthias", kind: "guard", cost: 1 },
  withEleven: { id: "withEleven", owner: "matthias", kind: "attack", cost: 1, damage: 20 },
  leaped: { id: "leaped", owner: "elizabeth", kind: "guard", cost: 1 },
  blessedAmong: { id: "blessedAmong", owner: "elizabeth", kind: "faith", cost: 2 },
  wouldNotBow: { id: "wouldNotBow", owner: "mordecai", kind: "guard", cost: 1 },
  suchATime: { id: "suchATime", owner: "mordecai", kind: "guard", cost: 1 },
  laughter: { id: "laughter", owner: "sarah", kind: "guard", cost: 1 },
  tooHard: { id: "tooHard", owner: "sarah", kind: "faith", cost: 2 },
  drinkMyLord: { id: "drinkMyLord", owner: "rebekah", kind: "guard", cost: 1 },
  waterCamels: { id: "waterCamels", owner: "rebekah", kind: "guard", cost: 2 },
  keepSheep: { id: "keepSheep", owner: "rachel", kind: "guard", cost: 1 },
  fewDays: { id: "fewDays", owner: "rachel", kind: "guard", cost: 1 },
  ifThouGo: { id: "ifThouGo", owner: "barak", kind: "guard", cost: 1 },
  downTabor: { id: "downTabor", owner: "barak", kind: "attack", cost: 1, damage: 30 },
  blessedAbove: { id: "blessedAbove", owner: "jael", kind: "guard", cost: 1 },
  tentPeg: { id: "tentPeg", owner: "jael", kind: "attack", cost: 2, damage: 40 },
  wentInBoldly: { id: "wentInBoldly", owner: "josephArimathea", kind: "guard", cost: 1 },
  fineLinen: { id: "fineLinen", owner: "josephArimathea", kind: "guard", cost: 1 },
  brotherSaul: { id: "brotherSaul", owner: "ananias", kind: "guard", cost: 1 },
  scalesFell: { id: "scalesFell", owner: "ananias", kind: "guard", cost: 1 },
  butIfNot: { id: "butIfNot", owner: "threeFriends", kind: "guard", cost: 1 },
  fourthMan: { id: "fourthMan", owner: "threeFriends", kind: "faith", cost: 3 },
  lordGave: { id: "lordGave", owner: "job", kind: "guard", cost: 1 },
  turnedCaptivity: { id: "turnedCaptivity", owner: "job", kind: "faith", cost: 2 },
  walkedWithGod: { id: "walkedWithGod", owner: "enoch", kind: "guard", cost: 1 },
  saintsCome: { id: "saintsCome", owner: "enoch", kind: "attack", cost: 2, damage: 40 },
  breadAndWine: { id: "breadAndWine", owner: "melchizedek", kind: "guard", cost: 1 },
  tenthOfAll: { id: "tenthOfAll", owner: "melchizedek", kind: "guard", cost: 2 },
  goUpAtOnce: { id: "goUpAtOnce", owner: "caleb", kind: "guard", cost: 1 },
  thisMountain: { id: "thisMountain", owner: "caleb", kind: "attack", cost: 2, damage: 40 },
  almondRod: { id: "almondRod", owner: "jeremiah", kind: "guard", cost: 1 },
  fireInBones: { id: "fireInBones", owner: "jeremiah", kind: "attack", cost: 1, damage: 30 },
  watchman: { id: "watchman", owner: "ezekiel", kind: "guard", cost: 1 },
  dryBones: { id: "dryBones", owner: "ezekiel", kind: "faith", cost: 3 },
  preparedHeart: { id: "preparedHeart", owner: "ezra", kind: "guard", cost: 1 },
  readTheLaw: { id: "readTheLaw", owner: "ezra", kind: "guard", cost: 2 },
  thouArtTheMan: { id: "thouArtTheMan", owner: "nathan", kind: "attack", cost: 1, damage: 30 },
  houseForever: { id: "houseForever", owner: "nathan", kind: "guard", cost: 1 },
  spreadLetter: { id: "spreadLetter", owner: "hezekiah", kind: "faith", cost: 3, damage: 50 },
  fifteenYears: { id: "fifteenYears", owner: "hezekiah", kind: "guard", cost: 1 },
  heardTheBook: { id: "heardTheBook", owner: "josiah", kind: "guard", cost: 1 },
  purgeIdols: { id: "purgeIdols", owner: "josiah", kind: "attack", cost: 2, damage: 40 },
  hisStar: { id: "hisStar", owner: "magi", kind: "guard", cost: 1 },
  threeGifts: { id: "threeGifts", owner: "magi", kind: "faith", cost: 3 },
  goodTidings: { id: "goodTidings", owner: "shepherds", kind: "guard", cost: 1 },
  gloryHighest: { id: "gloryHighest", owner: "shepherds", kind: "faith", cost: 2 },
  sonOfDavid: { id: "sonOfDavid", owner: "bartimaeus", kind: "guard", cost: 1 },
  castGarment: { id: "castGarment", owner: "bartimaeus", kind: "attack", cost: 1, damage: 30 },
  speakTheWord: { id: "speakTheWord", owner: "centurion", kind: "guard", cost: 2 },
  underAuthority: { id: "underAuthority", owner: "centurion", kind: "faith", cost: 2 },
  onlyBelieve: { id: "onlyBelieve", owner: "jairus", kind: "guard", cost: 1 },
  talithaCumi: { id: "talithaCumi", owner: "jairus", kind: "faith", cost: 2 },
  bearHisCross: { id: "bearHisCross", owner: "simonCyrene", kind: "guard", cost: 1 },
  comingFromCountry: { id: "comingFromCountry", owner: "simonCyrene", kind: "guard", cost: 1 },
  rememberMe: { id: "rememberMe", owner: "thief", kind: "guard", cost: 1 },
  paradise: { id: "paradise", owner: "thief", kind: "faith", cost: 1 },
  swiftToHear: { id: "swiftToHear", owner: "jamesJust", kind: "guard", cost: 1 },
  faithWorks: { id: "faithWorks", owner: "jamesJust", kind: "attack", cost: 1, damage: 20 },
  saveThyself: { id: "saveThyself", owner: "mockingThief", kind: "attack", cost: 1, damage: 30 },
  railedOn: { id: "railedOn", owner: "mockingThief", kind: "attack", cost: 2, damage: 50 },
  forgiveThem: { id: "forgiveThem", owner: "jesusCross", kind: "guard", cost: 1 },
  itIsFinished: { id: "itIsFinished", owner: "jesusCross", kind: "faith", cost: 3, damage: 60 },
  twoMites: { id: "twoMites", owner: "widow", kind: "guard", cost: 1 },
  allHerLiving: { id: "allHerLiving", owner: "widow", kind: "guard", cost: 1 },
  toiledAllNight: { id: "toiledAllNight", owner: "fisherman", kind: "guard", cost: 1 },
  atThyWord: { id: "atThyWord", owner: "fisherman", kind: "attack", cost: 1, damage: 20 },
  throughTheRoof: { id: "throughTheRoof", owner: "fourFriends", kind: "guard", cost: 1 },
  theirFaith: { id: "theirFaith", owner: "fourFriends", kind: "guard", cost: 2 },
  oilAndWine: { id: "oilAndWine", owner: "goodSamaritan", kind: "guard", cost: 1 },
  twoPence: { id: "twoPence", owner: "goodSamaritan", kind: "guard", cost: 1 },
  hardenedHeart: { id: "hardenedHeart", owner: "pharaoh", kind: "guard", cost: 1 },
  makeBricks: { id: "makeBricks", owner: "pharaoh", kind: "guard", cost: 1 },
  pursued: { id: "pursued", owner: "charioteer", kind: "attack", cost: 1, damage: 30 },
  chosenChariots: { id: "chosenChariots", owner: "charioteer", kind: "guard", cost: 1 },
  royalCommand: { id: "royalCommand", owner: "jezebel", kind: "guard", cost: 1 },
  sealedLetters: { id: "sealedLetters", owner: "jezebel", kind: "attack", cost: 2, damage: 40 },
  callOnBaal: { id: "callOnBaal", owner: "baalProphet", kind: "attack", cost: 1, damage: 20 },
  cutThemselves: { id: "cutThemselves", owner: "baalProphet", kind: "guard", cost: 1 },
  kingsRing: { id: "kingsRing", owner: "haman", kind: "guard", cost: 1 },
  hamansDecree: { id: "hamansDecree", owner: "haman", kind: "attack", cost: 2, damage: 30 },
  pieceOfSilver: { id: "pieceOfSilver", owner: "delilah", kind: "guard", cost: 1 },
  whereinStrength: { id: "whereinStrength", owner: "delilah", kind: "attack", cost: 2, damage: 40 },
  sevenTimesHotter: { id: "sevenTimesHotter", owner: "nebuchadnezzar", kind: "attack", cost: 2, damage: 30 },
  praiseKingOfHeaven: { id: "praiseKingOfHeaven", owner: "nebuchadnezzar", kind: "faith", cost: 2 },
  volley: { id: "volley", owner: "archerP", kind: "attack", cost: 1, damage: 40 },
  shieldUp: { id: "shieldUp", owner: "bearerP", kind: "guard", cost: 1 },
  bash: { id: "bash", owner: "bearerP", kind: "attack", cost: 1, damage: 20 },
  spearThrust: { id: "spearThrust", owner: "goliathP", kind: "attack", cost: 1, damage: 30 },
  taunt: { id: "taunt", owner: "goliathP", kind: "attack", cost: 2, damage: 10 },
  venom: { id: "venom", owner: "serpentP", kind: "attack", cost: 1, damage: 30 },
  beguile: { id: "beguile", owner: "serpentP", kind: "guard", cost: 3 },
};

export const CHARACTER_SKILLS: Record<CharacterId, SkillId[]> = {
  david: ["sling", "slingStone"],
  samuel: ["rebuke", "heal", "arise"],
  jonathan: ["sword", "covshield"],
  adam: ["till", "keep"],
  cain: ["offering", "mark"],
  abel: ["firstlings", "faithOffering"],
  noah: ["ark", "rainbow"],
  abraham: ["stars", "provide"],
  isaac: ["harvest", "ram"],
  jacob: ["wrestle", "ladder"],
  joseph: ["granary", "meantForGood"],
  moses: ["sea", "handsUp"],
  aaron: ["blessing", "breastplate"],
  miriam: ["timbrel", "song"],
  mosesSinai: ["tenWords", "faceShone"],
  joshua: ["courage", "jericho"],
  rahab: ["hideSpies", "scarletCord"],
  deborah: ["upToday", "starsFought"],
  gideon: ["fleece", "torches"],
  samson: ["jawbone", "pillars"],
  ruth: ["glean", "whither"],
  naomi: ["counsel", "restorer"],
  boaz: ["wings", "redeemer"],
  hannah: ["prayer", "hannahSong"],
  saul: ["javelin", "rashOffering"],
  abigail: ["provision", "intercede"],
  solomon: ["wisdom", "templeFire"],
  elijah: ["ravens", "carmel"],
  elisha: ["healWaters", "chariots"],
  jonah: ["castIntoSea", "nineveh"],
  isaiah: ["sendMe", "greatLight"],
  esther: ["fasting", "contrary"],
  daniel: ["stoneCut", "lionsDen"],
  nehemiah: ["buildWall", "swordAndTrowel"],
  zechariah: ["incense", "nameIsJohn"],
  mary: ["handmaid", "magnificat"],
  josephNaz: ["carpenter", "dreamWarning"],
  johnBaptist: ["axe", "baptism"],
  jesus: ["leper", "gethsemane"],
  jesusUR: ["walkOnWater", "loaves"],
  peter: ["greatCatch", "drawSword"],
  andrew: ["comeAndSee", "aLadHere"],
  johnApostle: ["thunder", "loveOneAnother"],
  matthew: ["taxBooth", "feast"],
  jamesZeb: ["mendNets", "boanerges"],
  thomas: ["reachFinger", "myLord"],
  maryMagdalene: ["spices", "seenTheLord"],
  martha: ["serving", "riseAgain"],
  zacchaeus: ["sycamore", "fourfold"],
  maryBethany: ["atHisFeet", "spikenard"],
  lazarus: ["looseHim", "manyBelieved"],
  stephen: ["gracePower", "heavensOpened"],
  philip: ["hereIsWater", "samaria"],
  paul: ["armourOfGod", "swordOfSpirit"],
  barnabas: ["encourage", "soldField"],
  silas: ["midnightHymns", "prisonOpened"],
  timothy: ["example", "stirUpGift"],
  lydia: ["purpleCloth", "abideHouse"],
  priscilla: ["tentmaking", "expound"],
  eli: ["goInPeace", "speakLord"],
  aquila: ["tentRope", "layDownNeck"],
  dorcas: ["garments", "almsdeeds"],
  cornelius: ["centurionCommand", "prayersAlms"],
  apollos: ["mightyScriptures", "watered"],
  phoebe: ["succourer", "bearLetter"],
  luke: ["physician", "inOrder"],
  johnMark: ["departed", "profitable"],
  titus: ["setInOrder", "earnestCare"],
  philemon: ["refreshed", "receiveHim"],
  onesimus: ["nowProfitable", "belovedBrother"],
  nicodemus: ["byNight", "bornAgain"],
  samaritan: ["livingWater", "comeSee"],
  simeon: ["waiting", "nuncDimittis"],
  anna: ["nightAndDay", "gaveThanks"],
  loavesBoy: ["giveBasket", "pebble"],
  judas: ["thirtySilver", "moneyBag"],
  philipApostle: ["philipComeSee", "twoHundredPence"],
  nathanael: ["figTree", "noGuile"],
  jamesAlph: ["quietFaith", "oneOfTwelve"],
  thaddaeus: ["aQuestion", "contendFaith"],
  simonZealot: ["zeal", "swordDown"],
  matthias: ["lotFell", "withEleven"],
  elizabeth: ["leaped", "blessedAmong"],
  mordecai: ["wouldNotBow", "suchATime"],
  sarah: ["laughter", "tooHard"],
  rebekah: ["drinkMyLord", "waterCamels"],
  rachel: ["keepSheep", "fewDays"],
  barak: ["ifThouGo", "downTabor"],
  jael: ["blessedAbove", "tentPeg"],
  josephArimathea: ["wentInBoldly", "fineLinen"],
  ananias: ["brotherSaul", "scalesFell"],
  threeFriends: ["butIfNot", "fourthMan"],
  job: ["lordGave", "turnedCaptivity"],
  enoch: ["walkedWithGod", "saintsCome"],
  melchizedek: ["breadAndWine", "tenthOfAll"],
  caleb: ["goUpAtOnce", "thisMountain"],
  jeremiah: ["almondRod", "fireInBones"],
  ezekiel: ["watchman", "dryBones"],
  ezra: ["preparedHeart", "readTheLaw"],
  nathan: ["thouArtTheMan", "houseForever"],
  hezekiah: ["spreadLetter", "fifteenYears"],
  josiah: ["heardTheBook", "purgeIdols"],
  magi: ["hisStar", "threeGifts"],
  shepherds: ["goodTidings", "gloryHighest"],
  bartimaeus: ["sonOfDavid", "castGarment"],
  centurion: ["speakTheWord", "underAuthority"],
  jairus: ["onlyBelieve", "talithaCumi"],
  simonCyrene: ["bearHisCross", "comingFromCountry"],
  thief: ["rememberMe", "paradise"],
  jamesJust: ["swiftToHear", "faithWorks"],
  mockingThief: ["saveThyself", "railedOn"],
  jesusCross: ["forgiveThem", "itIsFinished"],
  widow: ["twoMites", "allHerLiving"],
  fisherman: ["toiledAllNight", "atThyWord"],
  fourFriends: ["throughTheRoof", "theirFaith"],
  goodSamaritan: ["oilAndWine", "twoPence"],
  pharaoh: ["hardenedHeart", "makeBricks"],
  charioteer: ["chosenChariots", "pursued"],
  jezebel: ["royalCommand", "sealedLetters"],
  baalProphet: ["cutThemselves", "callOnBaal"],
  haman: ["kingsRing", "hamansDecree"],
  delilah: ["pieceOfSilver", "whereinStrength"],
  nebuchadnezzar: ["sevenTimesHotter", "praiseKingOfHeaven"],
  eve: ["mother", "helper"],
  archerP: ["volley"],
  bearerP: ["shieldUp", "bash"],
  goliathP: ["spearThrust", "taunt"],
  serpentP: ["venom", "beguile"],
};

export const CARDS_V2: Record<CardId, CardDef> = {
  delivered: { id: "delivered", energy: "faith" },
  battle: { id: "battle", energy: "faith" },
  trust: { id: "trust", energy: "faith" },
  assurance: { id: "assurance", energy: "faith" },
  inname: { id: "inname", energy: "attack" },
  trains: { id: "trains", energy: "attack" },
  stones: { id: "stones", energy: "attack" },
  wings: { id: "wings", energy: "guard" },
  shepherd: { id: "shepherd", energy: "guard" },
  renewed: { id: "renewed", energy: "guard" },
  bestrong: { id: "bestrong", energy: "guard" },
  covenant: { id: "covenant", energy: "guard" },
};

/** 15 energy cards: ✨ Faith 4, 🗡️ Attack 6, 🕊️ Guard 5. */
export const DECK_V2: CardId[] = [
  "delivered", "battle", "trust", "assurance",
  "inname", "inname", "trains", "trains", "stones", "stones",
  "wings", "shepherd", "renewed", "bestrong", "covenant",
];

export const PHASE1_CYCLE: GoliathActionId[] = ["defy", "spear", "raise", "crush"];
export const PHASE2_CYCLE: GoliathActionId[] = ["swing", "raise", "crush"];
/** The Serpent keeps one cycle; after shedding its skin (half HP) its fang hits harder. */
export const SERPENT_CYCLE: GoliathActionId[] = ["tempt", "fang", "coil", "fang"];
