import type { CardDef, CardId, CharacterId, Element, EnemyId, GoliathActionId, SkillDef, SkillId, StageId } from "./types";

// Prototype v2 (energy-card version) numbers. Change only with the designer's approval.
export const RULES_V2 = {
  openingHand: 5,
  drawPerTurn: 3,
  maxHand: 7,

  /** Faith and Guard carry over between turns up to these caps; Attack resets each turn. */
  maxFaith: 6,
  maxGuard: 6,
  /** David's passive "Against the Giant": while Faith ≥ this, David's attacks +giantBonus. */
  giantFaith: 3,
  giantBonus: 20,

  /** Victory when Goliath falls; the others flee (1 Sam 17:51). */
  archerDamage: 30,
  spear: 30,
  crush: 90,
  swing: 50,
  defyTargets: 2,

  healAmount: 50,
  ariseHp: 70,
  covShield: 30,
  /** The Serpent of Eden. Coil hits every ally. */
  fang: 60,
  fangShed: 80,
  coil: 40,
  temptFaith: 1,

  /** Story bonuses: a character fighting in their own Bible story. */
  /** Sling Stone away from Goliath: ordinary damage, no Stun. */
  slingStoneElsewhere: 80,
  /** Adam in Eden: Till the Ground +20, Keep the Garden Shield +30. */
  edenTillBonus: 20,
  edenKeepBonus: 30,
  /** Eve in Eden: Mother of All Living +20, and every ally's attacks on the Serpent +20 (Genesis 3:15). */
  edenMotherBonus: 20,
  edenSeedBonus: 20,

  /** Enemy cards played on the player's side. */
  shieldUpAmount: 50,

  /** Adam's Keep the Garden: Shield on himself. */
  keepShield: 50,
  /** Cain's Fruit of the Ground also gives Faith; his Mark strikes back at every enemy that hits him. */
  offeringFaith: 1,
  markRetaliate: 30,
  /** Abel's Firstlings of the Flock heals one ally; when he falls, Yet Speaketh shields every ally and gives Faith. */
  firstlingsHeal: 40,
  speakethShield: 30,
  speakethFaith: 1,
  /** Noah's Build the Ark shields every ally; his Rainbow Covenant (once per battle) heals every ally and lifts Shaken. */
  arkShield: 40,
  rainbowHeal: 50,
  /** Abraham's Look Toward Heaven gives Faith; The LORD Will Provide (once per battle) draws cards. */
  starsFaith: 2,
  provideDraw: 3,
  /** Isaac's Hundredfold Harvest hits harder with Abraham in the line-up; the Ram leaves a falling ally at this HP. */
  harvestBlessing: 20,
  ramHp: 10,
  /** Jacob's Wrestle Until Dawn costs him HP and wins the party Faith. */
  wrestleCost: 10,
  wrestleFaith: 1,
  /** Joseph's Storehouses heal and shield every ally; God Meant It for Good turns half the party's lost HP into damage. */
  granaryHeal: 30,
  granaryShield: 20,
  goodCap: 100,
  /** Moses' Hold Up His Hands: every ally's attacks this turn +20. */
  handsBonus: 20,
  /** Aaron's Blessing heals and shields one ally. */
  blessingHeal: 30,
  blessingShield: 30,
  /** Miriam's Song of the Sea gives Faith and lifts Shaken from everyone. */
  songFaith: 2,
  /** Moses at Sinai: The Ten Words shield every ally and give Faith. */
  tenWordsShield: 30,
  tenWordsFaith: 1,
  /** Rahab's Hide the Spies shields one ally. */
  hideShield: 40,
  /** Deborah's Up! This Is the Day gives Attack energy. */
  upTodayAttack: 2,
  /** Gideon's Sign of the Fleece gives Faith and draws a card. */
  fleeceFaith: 1,
  fleeceDraw: 1,
  /** Ruth's Gleaning draws cards. */
  gleanDraw: 2,
  /** Naomi's Counsel heals one ally (double for Ruth); Restorer of Life raises a fallen ally. */
  counselHeal: 30,
  restorerHp: 50,
  /** Boaz's Under His Wings shields one ally. */
  wingsShield: 60,
  /** Hannah's Silent Prayer gives Faith (more with Samuel beside her); her Song heals every ally. */
  prayerFaith: 1,
  prayerSamuelFaith: 2,
  hannahSongHeal: 40,
  /** Saul's Rash Offering gives Faith at once, but Saul is Shaken next turn. */
  rashFaith: 2,
  /** Abigail's Provision heals every ally; her Intercession softens every hit this turn. */
  provisionHeal: 20,
  intercedeBlock: 20,
  /** Solomon's Ask for Wisdom gives Faith and Attack; Fire from Heaven also heals every ally. */
  wisdomFaith: 1,
  wisdomAttack: 1,
  templeFireHeal: 30,
  /** Elijah's Fed by Ravens heals him and draws a card. */
  ravensHeal: 40,
  ravensDraw: 1,
  /** Elisha's Healing the Waters (double with Elijah beside him); Chariots of Fire shield every ally. */
  healWatersHeal: 20,
  chariotsShield: 50,
  /** Jonah comes back out of the fish with this HP, once per battle. */
  fishHp: 50,
  /** Esther's Fasting gives Faith at the cost of her HP. */
  fastingFaith: 2,
  fastingCost: 10,
  /** Nehemiah's wall: Shield to every ally, +10 per earlier course this battle, up to the cap. */
  wallShield: 20,
  wallStep: 10,
  wallCap: 50,
  /** Sword and Trowel also shields Nehemiah. */
  trowelShield: 20,
  /** Zechariah: Incense gives Faith and a small Shield to all; His Name Is John (from turn 3) heals all and gives Faith. */
  incenseFaith: 1,
  incenseShield: 10,
  johnTurn: 3,
  johnHeal: 40,
  johnFaith: 2,
  /** Mary's Handmaid gives Faith; the Magnificat takes a share of the leader's HP. */
  handmaidFaith: 1,
  magnificatShare: 0.25,
  /** Joseph of Nazareth's Carpenter's Hands shield and heal one ally (double for Mary). */
  carpenterShield: 30,
  carpenterHeal: 20,
  /** John the Baptist: the Axe hits wood enemies double; Baptism heals every ally (+1 Faith with Zechariah). */
  baptismHeal: 30,
  /** Jesus (risen): Peace Be unto You heals one ally; I Am with You Alway shields every ally and gives Faith; the Loaves feed everyone. */
  risenPeaceHeal: 50,
  alwayShield: 40,
  alwayFaith: 2,
  loavesHeal: 40,
  loavesDraw: 3,
  loavesFaith: 1,
  /** Jesus (UR) rises on the third day: two turns after the turn he falls, with full HP. */
  riseAfter: 2,
  /** Peter: the Great Catch draws cards and gives Attack; his attacks are stronger with Jesus beside him. */
  catchDraw: 2,
  catchAttack: 1,
  peterWithJesus: 20,
  /** Andrew's A Lad Here draws cards and gives Faith. */
  ladDraw: 2,
  ladFaith: 1,
  /** John the Apostle's Love One Another heals and shields every ally (double with Jesus beside him). */
  loveHeal: 20,
  loveShield: 20,
  /** Matthew: Leaving the Tax Booth turns Guard into Attack; the Feast heals every ally and draws a card. */
  taxBoothAttack: 2,
  feastHeal: 30,
  feastDraw: 1,
  /** James: Mending the Nets heals one ally; Boanerges hits harder with John; when he falls, every attack +10. */
  mendHeal: 30,
  boanergesWithJohn: 20,
  cupBonus: 10,
  /** Thomas: Reach Hither Thy Finger gives Faith and makes him believe. */
  fingerFaith: 1,
  /** Mary Magdalene: Spices heal one ally; I Have Seen the Lord raises a fallen ally (Jesus at once, in full). */
  spicesHeal: 30,
  seenHp: 60,
  /** Martha: Serving turns Attack into Guard; Thy Brother Shall Rise Again brings the next fallen ally back with this HP. */
  servingGuard: 2,
  riseAgainHp: 50,
  /** Zacchaeus: the Sycamore gives Faith; Restore Fourfold gives Attack and Faith. */
  sycamoreFaith: 1,
  fourfoldAttack: 2,
  fourfoldFaith: 2,
  /** Mary of Bethany: At His Feet gives Faith (+1 Guard with Martha); Spikenard heals and shields every ally. */
  feetFaith: 2,
  spikenardHeal: 30,
  spikenardShield: 30,
  /** Lazarus: Loose Him shields and steadies one ally; Many Believed gives Faith and heals everyone a little. */
  looseShield: 30,
  believedFaith: 1,
  believedHeal: 10,
  /** Stephen's Heavens Opened heals every ally and lifts Shaken. */
  heavensHeal: 40,
  /** Philip: Here Is Water heals and steadies one ally; Preaching in Samaria hits every enemy and gives Faith. */
  waterHeal: 30,
  samariaFaith: 1,
  /** Paul: the Armour of God shields and steadies every ally; the Sword of the Spirit gives Faith; weak, he is strong. */
  armourShield: 30,
  swordFaith: 1,
  strongWhenWeak: 20,
  /** Barnabas: Encouragement steadies everyone and gives Attack (and shields Paul); Sold His Field gives Faith once. */
  encourageAttack: 1,
  encouragePaulShield: 30,
  fieldFaith: 3,
  /** Silas: Hymns at Midnight steady everyone and give Faith (more with Paul). */
  hymnsFaith: 1,
  hymnsPaulFaith: 2,
  /** Timothy: Be an Example strengthens every attack this turn; Stir Up the Gift hits harder with Paul. */
  exampleBonus: 10,
  stirWithPaul: 20,
  /** Lydia: Purple Cloth shields one ally and gives Faith; Abide in My House heals everyone (+1 Faith with Paul or Silas). */
  purpleShield: 30,
  purpleFaith: 1,
  abideHeal: 30,
  /** Priscilla: Tentmaking shields every ally; Expounding the Way strengthens one ally's attacks this turn. */
  tentShield: 20,
  expoundBonus: 30,
  /** Eli: Go in Peace heals one ally and gives Faith (double for Hannah); Speak, Lord lets an ally act again. */
  peaceHeal: 20,
  peaceFaith: 1,
  /** Aquila shields himself when he steps in front, with Priscilla beside him. */
  aquilaShield: 20,
  /** Dorcas: Garments heal and shield every ally a little; Almsdeeds heals one ally. */
  garmentHeal: 10,
  garmentShield: 10,
  almsHeal: 30,
  /** Cornelius' Prayers and Alms give Faith (+1 Attack with Peter in the line-up). */
  memorialFaith: 1,
  /** Apollos: Mighty in the Scriptures hits harder with Priscilla or Aquila; Watered heals every ally. */
  scripturesWithTeachers: 20,
  wateredHeal: 20,
  /** Phoebe: Succourer of Many heals one ally and gives Guard; Bearer of the Letter gives Faith and draws (more with Paul). */
  succourHeal: 30,
  letterFaith: 1,
  letterDraw: 1,
  /** Luke: the Beloved Physician heals one ally (double for Paul); In Order draws cards; with Paul he is shielded each turn. */
  physicianHeal: 40,
  orderDraw: 2,
  lukeShield: 10,
  /** John Mark: Departing gives Faith but he is Shaken next turn; Profitable hits harder with Barnabas or Paul. */
  departFaith: 2,
  profitableWith: 20,
  /** Titus: Set in Order gives a Guard and an Attack; Earnest Care shields every ally (more with Paul). */
  earnestShield: 20,
  earnestPaulShield: 30,
  /** Philemon: Refreshed heals and steadies every ally; Receive Him raises a fallen ally (more with Paul). */
  refreshHeal: 20,
  receiveHp: 50,
  receivePaulHp: 80,
  /** Onesimus' Brother Beloved gives Faith. */
  brotherFaith: 1,
  /** Nicodemus: By Night draws (2 with Jesus) and gives Faith. */
  nightDraw: 1,
  nightFaith: 1,
  /** The Samaritan woman: Living Water heals every ally (double with Jesus). */
  livingHeal: 20,
  /** Simeon: Nunc Dimittis heals and shields everyone, then Simeon departs in peace. */
  nuncHeal: 40,
  nuncShield: 20,
  /** Anna: Night and Day shields everyone a little and gives Faith; Gave Thanks gives Faith (2 with Simeon). */
  annaShield: 10,
  /** The boy with the loaves: the Basket gives Faith (and heals everyone with Jesus). */
  basketFaith: 3,
  /** Elizabeth: the babe Leaped heals everyone (+1 Faith with Mary or John the Baptist); Blessed Among Women heals and shields an ally (double for Mary). */
  leapHeal: 20,
  blessedHeal: 40,
  blessedShield: 20,
  /** Mordecai: Would Not Bow shields him and steadies every ally; For Such a Time gives Faith (2 with Esther). */
  bowShield: 30,
  /** Sarah: Laughter heals everyone and gives Faith (2 with Abraham or Isaac); Too Hard restores an ally to full HP once. */
  laughHeal: 20,
  /** Rebekah: Drink, My Lord heals an ally; Water for the Camels heals and shields everyone (+1 Faith with Isaac). */
  drinkHeal: 30,
  camelsHeal: 20,
  camelsShield: 10,
  /** Rachel: Keeping the Sheep shields everyone (double with Jacob or Joseph); A Few Days gives Faith (2 with Jacob). */
  sheepShield: 10,
  /** Barak: If Thou Wilt Go gives Attack (2 with Deborah); Down from Tabor strikes (+20 with Deborah). */
  thouGoAttack: 1,
  /** Jael: the Tent Peg strikes hard (+30 on a foe at half HP or less). */
  pegFinish: 30,
  /** Joseph of Arimathea: Fine Linen heals and shields an ally; his new tomb lets Jesus (UR) rise a turn sooner. */
  linenHeal: 30,
  linenShield: 20,
  /** Ananias: Brother Saul heals an ally (double for Paul); the Scales Fell steadies and shields everyone (+1 Faith with Paul). */
  brotherHeal: 30,
  scalesShield: 10,
  /** Job: the LORD Gave shields him (+1 Faith when at half HP or less); Turned His Captivity restores him twice over, once. */
  jobShield: 30,
  captivityShieldMax: 60,
  /** Enoch: Walked with God gives Faith and shields him; when God takes him, every ally heals and the team gains Faith. */
  walkShield: 20,
  takenHeal: 30,
  takenFaith: 2,
  /** Melchizedek: Bread and Wine heals everyone (+1 Faith with Abraham); Tithes of All gives Faith (3 with Abraham). */
  breadHeal: 20,
  titheFaith: 2,
  /** Caleb: Go Up at Once gives Attack (2 with Joshua) and steadies everyone; Give Me This Mountain hits harder while he is at full HP. */
  goUpAttack: 1,
  stillStrong: 20,
  /** Jeremiah: the Almond Rod draws a card and gives Faith; Fire in My Bones burns hotter when he is at half HP or less. */
  bonesBonus: 20,
  /** Ezekiel: the Watchman shields everyone and gives Faith; the Dry Bones Live raises every fallen ally, once. */
  watchmanShield: 10,
  dryBonesHp: 30,
  /** Ezra: Prepared His Heart draws cards; Read in the Book gives Faith (3 with Nehemiah) and steadies everyone. */
  ezraDraw: 2,
  lawFaith: 2,
  /** Nathan: Thou Art the Man strikes the leader harder; Thy House Established shields everyone (David and Solomon most). */
  manBonus: 20,
  houseShield: 10,
  houseKingShield: 30,
  /** Hezekiah: Fifteen Years heals him (double with Isaiah); Spread the Letter strikes every enemy once. */
  fifteenHeal: 50,
  /** The Magi: His Star gives Faith (2 with Mary or Jesus); the Three Gifts give Attack, heal and shield everyone, once. */
  giftAttack: 2,
  giftHeal: 20,
  giftShield: 20,
  /** The shepherds: Good Tidings steadies everyone; Glory to God heals and shields everyone. */
  gloryHeal: 20,
  gloryShield: 10,
  /** Bartimaeus: Son of David gives Faith (2 with Jesus); Casting Away His Garment strikes (+20 with Jesus). */
  garmentWithJesus: 20,
  /** The centurion: Speak the Word heals another ally from afar (more with Jesus); Under Authority sends an ally to act again. */
  wordHeal: 40,
  wordHealJesus: 60,
  /** Jairus: Only Believe gives Faith (2 with Jesus); Talitha Cumi raises a fallen ally once (full HP with Jesus). */
  talithaHp: 50,
  /** Simon of Cyrene: Bear His Cross takes an ally's blows this turn and shields Simon; Out of the Country heals him. */
  crossShield: 20,
  countryHeal: 30,
  /** The penitent thief: Remember Me gives Faith (2 with Jesus); To Day in Paradise heals everyone and gives Faith, then he departs. */
  paradiseHeal: 40,
  paradiseFaith: 2,
  /** James the Lord's brother: Swift to Hear shields everyone (+1 Faith with Peter or Paul); Faith with Works grows with the Faith held. */
  hearShield: 10,
  worksPerFaith: 10,
  worksMax: 30,
  /** The criminal who mocked: Railed On hits hard, but the railing costs him HP. */
  railCost: 20,
  /** Jesus on the cross: Into Thy Hands strikes every enemy and heals every ally, then he gives up the ghost. */
  spiritHeal: 40,
  /** The four friends: Through the Roof heals another ally (double with Jesus); Their Faith gives Faith (3 with Jesus). */
  roofHeal: 30,
  theirFaith: 2,
  /** The good Samaritan: Oil and Wine heals another ally; Two Pence heals an ally at the start of each of the next 2 turns. */
  oilHeal: 40,
  innHeal: 20,
  innTurns: 2,
  /** Pharaoh: a Hardened Heart shields him; More Bricks gives Attack at the cost of every other ally's HP. */
  hardShield: 30,
  bricksAttack: 2,
  bricksCost: 10,
  /** The Egyptian charioteer: Pursued strikes (+20 with Pharaoh); Chosen Chariots give Attack and shield him. */
  chariotShield: 10,
  /** Jezebel: Royal Command gives Attack and shields her; Sealed Letters reach any enemy, even behind the shield bearer. */
  queenShield: 20,
  /** The prophet of Baal: Call on Baal grows louder each turn; Cut Themselves gives Attack at the cost of his HP. */
  baalPerTurn: 10,
  baalMax: 40,
  cutCost: 20,
  cutAttack: 2,
  /** Haman: the King's Ring gives Attack; the Decree strikes every enemy, but with Esther or Mordecai it comes back on him. */
  ringAttack: 2,
  gallowsCost: 30,
  /** Nebuchadnezzar: Seven Times Hotter strikes every enemy; Praise the King of Heaven heals everyone and gives Faith, once. */
  heavenHeal: 30,
  heavenFaith: 2,
  /** Ahab: Coveting the Vineyard gives Attack (3 with Jezebel); Humbled Himself heals him and steadies everyone, once. */
  vineyardAttack: 2,
  humbledHeal: 50,
  /** The widow of Zarephath: the Meal Not Spent heals everyone a little (double with Elijah); the Little Cake heals another ally. */
  mealHeal: 10,
  cakeHeal: 30,
  /** The Shunammite woman: a Little Chamber shields everyone (more with Elisha); It Is Well raises a fallen ally once. */
  chamberShield: 10,
  wellHp: 60,
  /** Naaman: Seven Times in Jordan restores him and steadies everyone, once (+2 Faith with Elisha); Captain of the Host strikes. */
  jordanFaith: 2,
  /** The little maid: Would God gives Faith (2 with Naaman or Elisha); her service heals another ally. */
  maidHeal: 20,
  /** Bathsheba: Remember the Oath gives Faith (2 with David or Nathan); the King's Mother heals and shields an ally (double for Solomon). */
  queenMotherHeal: 40,
  queenMotherShield: 20,
  /** Absalom: Stole the Hearts gives Faith (3) but shakes David; Fifty Men Before Him strikes (+20 against the leader). */
  heartsFaith: 3,
  /** Mephibosheth: the King's Table heals him (double with David or Jonathan) and gives Faith; a Dead Dog steadies everyone. */
  tableHeal: 30,
  /** The Queen of Sheba: Hard Questions draw cards (2 with Solomon) and give Faith; Spices and Gold give Attack and heal everyone. */
  goldAttack: 2,
  spiceHeal: 20,
  /** Leah: Looked Upon My Affliction heals her (+1 Faith when she is at half HP or less); Now Will I Praise gives Faith (3 with Jacob). */
  afflictionHeal: 30,
  praiseFaith: 2,
  /** Esau: the Cunning Hunter strikes (+20 with Isaac); Ran to Meet Him steadies and shields everyone (Jacob most). */
  hunterWithIsaac: 20,
  embraceShield: 10,
  embraceJacobShield: 30,
  /** Hagar and Ishmael: God Heard gives Faith (3 with Abraham) and heals them; the Well Opened heals everyone, once. */
  heardHeal: 20,
  wellHeal: 40,
  /** Lot and his wife: Escape for Thy Life shields everyone (+1 Faith with Abraham); Looking Back gives Attack but shakes them. */
  escapeShield: 15,
  lookBackAttack: 2,
  /** Jochebed: the Ark of Bulrushes shields another ally (Moses most); Nurse Him heals another ally and gives Faith (2 with Moses or Miriam). */
  bulrushShield: 30,
  bulrushMosesShield: 60,
  nurseHeal: 30,
  /** Pharaoh's daughter: Had Compassion heals another ally (double for Moses); Drew Him Out gives Faith (3 with Moses or Jochebed). */
  compassionHeal: 40,
  drewFaith: 2,
  /** Jethro: Share the Burden gives Attack and Guard (+1 Faith with Moses); Greater Than All Gods gives Faith (3 with Moses). */
  greaterFaith: 2,
  /** Zipporah: Watered the Flock heals everyone (and shields them with Moses); a Stranger in a Strange Land gives Faith (2 with Moses or Jethro). */
  flockHeal: 15,
  flockShield: 10,
  /** Lois and Eunice: Unfeigned Faith gives Faith (2 with Timothy); From a Child draws a card and shields everyone (Timothy most). */
  childShield: 10,
  childTimothyShield: 30,
  /** Ananias and Sapphira: Sold a Possession gives Attack; Kept Back Part gives Faith — but with Peter in the line-up the lie is found out. */
  soldAttack: 2,
  keptFaith: 3,
  keptCost: 30,
  /** Pilate: No Fault shields everyone; Washed His Hands guards himself and gives Attack, but strips every other ally's Shield. */
  noFaultShield: 15,
  washShield: 30,
  /** Caiaphas: One Man Should Die gives Faith at the cost of the sturdiest other ally's HP; Rent His Clothes strikes. */
  expedientFaith: 3,
  expedientCost: 20,
  /** Herod Antipas: Hoped to See a Miracle draws cards; the Gorgeous Robe shields him and gives Attack (+1 Faith with Pilate). */
  signDraw: 2,
  robeShield: 20,
  /** Barabbas: Insurrection strikes; Released unto Them restores him once (+2 Faith with Jesus — another took his place). */
  releasedFaith: 2,
  /** Herodias: a Convenient Day gives Attack (+1 Faith with Herod); the Grudge strikes hard, but shakes John the Baptist. */
  convenientAttack: 2,
  /** The Roman infantryman: Shield Wall shields him and the ally beside him; the Gladius strikes (+20 under a centurion). */
  scutumShield: 30,
  wallAllyShield: 10,
  underCenturion: 20,
  /** Sennacherib: On Whom Dost Thou Trust gives Attack; the Fenced Cities strike every enemy — but with Hezekiah, the angel of the LORD smites his camp. */
  campSmitten: 50,
  /** Belshazzar: the Golden Vessels give Attack but shake him; the Writing on the Wall gives Faith (3 with Daniel, who is clothed in scarlet). */
  vesselsAttack: 3,
  scarletShield: 20,
  /** Balaam and his donkey: the Donkey Saw the Angel shields and steadies everyone; Bless, Not Curse heals everyone and gives Faith. */
  donkeyShield: 15,
  blessHeal: 20,
  /** Korah: Ye Take Too Much gives Attack but shakes Moses and Aaron; the Censers strike every enemy, but with Moses or Aaron the earth opens. */
  censerCost: 40,
  /** Achan: the Hidden Spoil gives Faith, but with Joshua it is found out; the Trouble of Achor strikes every enemy at his own cost. */
  spoilFaith: 3,
  spoilCost: 30,
  achorCost: 20,
  /** Sisera: his chariots strike every enemy, but Deborah or Barak rout them; fleeing to the tent heals him, unless Jael is there. */
  siseraMilkHeal: 20,
  siseraMantleShield: 30,
  siseraPegCost: 40,
  /** Herod the Great: Privily Called draws cards, but the Magi or Joseph foil him; Exceeding Wroth strikes hard at his own cost. */
  privilyDraw: 2,
  wrothCost: 15,
  /** The man freed from Legion: In His Right Mind steadies everyone (Faith with Jesus); Tell How Great draws and heals everyone. */
  legionShield: 30,
  legionFaith: 2,
  tellDraw: 2,
  tellHeal: 15,
  /** The prodigal son: Came to Himself gives more Faith the lower he has sunk; the Best Robe heals and covers him. */
  prodigalFaith: 1,
  prodigalLowFaith: 3,
  prodigalRobeHeal: 40,
  prodigalRobeShield: 20,
  /** The Ethiopian: reading Isaiah gives Faith (more with Philip to guide him); he went on his way rejoicing. */
  eunuchFaith: 1,
  eunuchPhilipFaith: 3,
  rejoicingHeal: 20,
  /** John on Patmos: In the Spirit gives Faith and a card; a New Heaven heals and steadies every ally. */
  patmosFaith: 2,
  newHeavenHeal: 30,
  /** Ehud: the left-handed dagger strikes harder at an enemy still unhurt; his trumpet gives Attack and covers him. */
  ehudSurprise: 20,
  trumpetAttack: 2,
  trumpetShield: 20,
  /** Jephthah: The LORD Be Judge gives Faith and Shield; his rash vow strikes hard but costs him dearly. */
  judgeFaith: 2,
  judgeShield: 15,
  vowCost: 30,
  /** Joab: Play the Men shields every ally and gives Attack; his three darts strike hard, and with Absalom on the team they find him too. */
  joabShield: 15,
  dartsCost: 40,
  /** Uriah: Would Not Go Home shields him and gives Faith; set in the hottest battle he strikes hard at his own cost, more with David there. */
  uriahShield: 30,
  uriahFaith: 1,
  hottestCost: 20,
  hottestBetrayed: 40,
  /** Simon the sorcerer: his sorceries give Attack (Faith instead with Philip); offering money turns Attack into Faith, unless Peter is there. */
  sorceryAttack: 2,
  sorceryFaith: 2,
  /** Herod Agrippa I: pleasing the crowd gives Attack, unless Peter is there to be set free; the voice of a god strikes every enemy, then the angel smites him. */
  agrippaAttack: 2,
  voiceCost: 40,
  /** Cyrus: his decree gives Faith (and Attack with Ezra, Nehemiah or Daniel to go up); returning the temple vessels shields every ally. */
  cyrusFaith: 2,
  cyrusShield: 25,
  /** Zerubbabel: laying the foundation shields him and gives Faith; Not by Might strikes every enemy with Faith alone. */
  foundationShield: 30,
  foundationFaith: 1,
  /** Vashti: refusing to come shields her; her feast heals every ally (Faith too with Esther there). */
  vashtiShield: 40,
  vashtiFeastHeal: 20,
  /** Michal: Let Down Through a Window shields another ally (more for David) and steadies them; the image in the bed draws a card and shields her. */
  michalShield: 30,
  michalDavidShield: 50,
  michalDecoyShield: 20,
  /** Gehazi: running after Naaman gives Attack, unless Elisha is there to see it; two talents give Faith and a card. */
  gehaziAttack: 2,
  gehaziCost: 30,
  /** Jehu: his zeal gives Attack and shakes any of Ahab's house on the team. */
  jehuAttack: 2,
  /** The Roman spearman: Brace Spears takes an ally's blows this turn and shields him; the Pilum reaches any enemy. */
  braceShield: 20,
  basketHeal: 30,
  /** Judas: Thirty Pieces of Silver give Faith at an ally's cost; the Money Bag strikes and gives Faith. */
  silverFaith: 3,
  silverCost: 20,

  /** Eve's Mother of All Living: heals every ally. */
  motherHeal: 40,

  /** Elements are reserved for multi-stage play: switched off, so damage is unaffected for now. */
  elements: {
    enabled: true,
    /** Attacker's element beats the defender's. */
    strong: 1.5,
    /** Defender's element beats the attacker's (water/fire/wood cycle). */
    weak: 0.75,
  },

  /** Delay between Goliath's action and the next turn in the UI (ms). */
  stepDelay: 800,
} as const;

/**
 * Which elements each element beats: the five phases' overcoming cycle (wood → earth → water → fire → metal → wood),
 * plus light and dark countering each other. Every element beats one and is beaten by one; light and dark are
 * neutral to the five phases.
 */
export const ELEMENT_BEATS: Record<Element, Element[]> = {
  wood: ["earth"],
  earth: ["water"],
  water: ["fire"],
  fire: ["metal"],
  metal: ["wood"],
  light: ["dark"],
  dark: ["light"],
};

/** Adam is earth (formed from the dust, Genesis 2:7); Goliath is metal (bronze armour, 1 Samuel 17:5-7). */
export const CHARACTER_ELEMENT: Record<CharacterId, Element> = {
  david: "light",
  samuel: "water",
  jonathan: "fire",
  adam: "earth",
  cain: "earth",
  abel: "light",
  noah: "water",
  abraham: "metal",
  isaac: "wood",
  jacob: "earth",
  joseph: "metal",
  moses: "fire",
  aaron: "light",
  miriam: "water",
  mosesSinai: "light",
  joshua: "metal",
  rahab: "fire",
  deborah: "wood",
  gideon: "fire",
  samson: "earth",
  ruth: "wood",
  naomi: "water",
  boaz: "metal",
  hannah: "water",
  saul: "metal",
  abigail: "light",
  solomon: "fire",
  elijah: "fire",
  elisha: "water",
  jonah: "water",
  isaiah: "light",
  esther: "metal",
  daniel: "earth",
  nehemiah: "earth",
  zechariah: "light",
  mary: "wood",
  josephNaz: "wood",
  johnBaptist: "water",
  jesus: "light",
  jesusUR: "light",
  peter: "earth",
  andrew: "water",
  johnApostle: "fire",
  matthew: "metal",
  jamesZeb: "fire",
  thomas: "wood",
  maryMagdalene: "wood",
  martha: "earth",
  zacchaeus: "metal",
  maryBethany: "wood",
  lazarus: "earth",
  stephen: "light",
  philip: "water",
  paul: "metal",
  barnabas: "earth",
  silas: "metal",
  timothy: "fire",
  lydia: "water",
  priscilla: "wood",
  eli: "fire",
  aquila: "earth",
  dorcas: "wood",
  cornelius: "metal",
  apollos: "water",
  phoebe: "water",
  luke: "water",
  johnMark: "wood",
  titus: "earth",
  philemon: "wood",
  onesimus: "wood",
  nicodemus: "water",
  samaritan: "water",
  simeon: "light",
  anna: "light",
  elizabeth: "wood",
  mordecai: "metal",
  sarah: "earth",
  rebekah: "water",
  rachel: "wood",
  barak: "earth",
  jael: "metal",
  josephArimathea: "light",
  ananias: "water",
  threeFriends: "fire",
  job: "earth",
  enoch: "light",
  melchizedek: "light",
  caleb: "earth",
  jeremiah: "fire",
  ezekiel: "wood",
  ezra: "water",
  nathan: "metal",
  hezekiah: "water",
  josiah: "fire",
  magi: "light",
  shepherds: "wood",
  bartimaeus: "light",
  centurion: "metal",
  jairus: "earth",
  simonCyrene: "earth",
  thief: "light",
  jamesJust: "earth",
  mockingThief: "dark",
  jesusCross: "light",
  widow: "earth",
  fisherman: "water",
  fourFriends: "earth",
  goodSamaritan: "wood",
  legionFreed: "water",
  prodigal: "earth",
  ethiopian: "light",
  johnPatmos: "light",
  ehud: "metal",
  jephthah: "earth",
  joab: "metal",
  uriah: "earth",
  cyrus: "light",
  zerubbabel: "earth",
  vashti: "water",
  michal: "wood",
  gehazi: "dark",
  jehu: "fire",
  simonMagus: "dark",
  herodAgrippa: "metal",
  zarephath: "earth",
  shunammite: "wood",
  naaman: "water",
  maid: "light",
  bathsheba: "metal",
  mephibosheth: "earth",
  sheba: "metal",
  leah: "earth",
  esau: "fire",
  hagar: "water",
  lot: "earth",
  jochebed: "water",
  pharaohDaughter: "water",
  jethro: "earth",
  zipporah: "water",
  loisEunice: "wood",
  balaam: "earth",
  pharaoh: "metal",
  charioteer: "metal",
  jezebel: "dark",
  baalProphet: "dark",
  haman: "dark",
  delilah: "dark",
  nebuchadnezzar: "fire",
  ahab: "dark",
  absalom: "fire",
  sapphira: "dark",
  pilate: "metal",
  caiaphas: "dark",
  herod: "fire",
  barabbas: "dark",
  herodias: "dark",
  romanSoldier: "metal",
  romanSpearman: "metal",
  romanArcher: "metal",
  romanCavalry: "metal",
  romanCenturion: "metal",
  sennacherib: "dark",
  belshazzar: "metal",
  korah: "fire",
  achan: "earth",
  sisera: "metal",
  herodGreat: "dark",
  loavesBoy: "earth",
  judas: "dark",
  philipApostle: "earth",
  nathanael: "wood",
  jamesAlph: "earth",
  thaddaeus: "water",
  simonZealot: "fire",
  matthias: "light",
  eve: "wood",
  archerP: "fire",
  bearerP: "wood",
  goliathP: "metal",
  serpentP: "dark",
};
export const ENEMY_ELEMENT: Record<EnemyId, Element> = { bearer: "wood", goliath: "metal", archer: "fire", serpent: "dark" };

/** Cards that show the same person: a line-up holds only one of them. */
export const PERSON: Partial<Record<CharacterId, CharacterId>> = { mosesSinai: "moses", jesusUR: "jesus", jesusCross: "jesus", johnPatmos: "johnApostle" };

/** The twelve apostles (Matthew 10:2-4), for One of the Twelve. */
export const APOSTLES: ReadonlySet<CharacterId> = new Set(["peter", "andrew", "jamesZeb", "johnApostle", "johnPatmos", "philipApostle", "nathanael", "thomas", "matthew", "jamesAlph", "thaddaeus", "simonZealot", "judas", "matthias"]);

/** Cards that never fall: never targeted, never hurt, and not counted when deciding defeat. */
export const NEVER_FALLS: ReadonlySet<CharacterId> = new Set(["jesus"]);
export const personOf = (id: CharacterId): CharacterId => PERSON[id] ?? id;

/** Every playable character, in display order. */
export const PARTY_ORDER: CharacterId[] = ["david", "samuel", "jonathan", "adam", "eve", "cain", "abel", "noah", "abraham", "isaac", "jacob", "joseph", "moses", "aaron", "miriam", "mosesSinai", "joshua", "rahab", "deborah", "gideon", "samson", "ruth", "naomi", "boaz", "hannah", "saul", "abigail", "solomon", "elijah", "elisha", "jonah", "isaiah", "esther", "daniel", "nehemiah", "zechariah", "mary", "josephNaz", "johnBaptist", "jesus", "jesusUR", "peter", "andrew", "johnApostle", "matthew", "jamesZeb", "thomas", "maryMagdalene", "martha", "zacchaeus", "maryBethany", "lazarus", "stephen", "philip", "paul", "barnabas", "silas", "timothy", "lydia", "priscilla", "eli", "aquila", "dorcas", "cornelius", "apollos", "phoebe", "luke", "johnMark", "titus", "philemon", "onesimus", "nicodemus", "samaritan", "simeon", "anna", "loavesBoy", "judas", "philipApostle", "nathanael", "jamesAlph", "thaddaeus", "simonZealot", "matthias", "elizabeth", "mordecai", "sarah", "rebekah", "rachel", "barak", "jael", "josephArimathea", "ananias", "threeFriends", "job", "enoch", "melchizedek", "caleb", "jeremiah", "ezekiel", "ezra", "nathan", "hezekiah", "josiah", "magi", "shepherds", "bartimaeus", "centurion", "jairus", "simonCyrene", "thief", "jamesJust", "jesusCross", "widow", "fisherman", "fourFriends", "goodSamaritan", "zarephath", "shunammite", "naaman", "maid", "bathsheba", "mephibosheth", "sheba", "leah", "esau", "hagar", "lot", "jochebed", "pharaohDaughter", "jethro", "zipporah", "loisEunice", "balaam", "mockingThief", "pharaoh", "charioteer", "jezebel", "baalProphet", "haman", "delilah", "nebuchadnezzar", "ahab", "absalom", "sapphira", "pilate", "caiaphas", "herod", "barabbas", "herodias", "romanSoldier", "romanSpearman", "romanArcher", "romanCavalry", "romanCenturion", "sennacherib", "belshazzar", "korah", "achan", "sisera", "herodGreat", "legionFreed", "prodigal", "ethiopian", "johnPatmos", "ehud", "jephthah", "joab", "uriah", "cyrus", "zerubbabel", "vashti", "michal", "gehazi", "jehu", "simonMagus", "herodAgrippa", "goliathP", "serpentP", "bearerP", "archerP"];
/** Who fights when no line-up is chosen (the v2 battle). */
export const DEFAULT_LINEUP: CharacterId[] = ["david", "samuel", "jonathan"];

export const ENEMY_ORDER: EnemyId[] = ["bearer", "goliath", "archer", "serpent"];

/** Each character's own Bible story: fighting in that stage turns on their story bonus. */
export const STORY: Partial<Record<CharacterId, StageId>> = { david: "goliath", adam: "eden", eve: "eden" };

/** Who fights in each stage, and the boss. */
export const STAGE_ENEMIES: Record<StageId, EnemyId[]> = { goliath: ["bearer", "goliath", "archer"], eden: ["serpent"] };
export const STAGE_BOSS: Record<StageId, EnemyId> = { goliath: "goliath", eden: "serpent" };

/** HP and damage use Pokémon-TCG-style numbers (steps of 10). */
export const ENEMY_HP: Record<EnemyId, number> = { bearer: 60, goliath: 220, archer: 40, serpent: 250 };

export const MAX_HP: Record<CharacterId, number> = { david: 120, samuel: 100, jonathan: 140, adam: 130, eve: 120, cain: 120, abel: 120, noah: 140, abraham: 130, isaac: 100, jacob: 130, joseph: 120, moses: 130, aaron: 130, miriam: 100, mosesSinai: 130, joshua: 140, rahab: 100, deborah: 110, gideon: 120, samson: 150, ruth: 120, naomi: 90, boaz: 130, hannah: 100, saul: 150, abigail: 100, solomon: 130, elijah: 120, elisha: 120, jonah: 110, isaiah: 110, esther: 110, daniel: 130, nehemiah: 130, zechariah: 100, mary: 110, josephNaz: 130, johnBaptist: 120, jesus: 100, jesusUR: 150, peter: 140, andrew: 110, johnApostle: 110, matthew: 110, jamesZeb: 120, thomas: 110, maryMagdalene: 110, martha: 120, zacchaeus: 90, maryBethany: 100, lazarus: 120, stephen: 110, philip: 110, paul: 130, barnabas: 120, silas: 110, timothy: 100, lydia: 110, priscilla: 110, eli: 90, aquila: 110, dorcas: 100, cornelius: 140, apollos: 110, phoebe: 100, luke: 110, johnMark: 100, titus: 120, philemon: 110, onesimus: 90, nicodemus: 110, samaritan: 100, simeon: 100, anna: 90, loavesBoy: 80, judas: 100, philipApostle: 110, nathanael: 110, jamesAlph: 120, thaddaeus: 110, simonZealot: 120, matthias: 110, elizabeth: 100, mordecai: 130, sarah: 110, rebekah: 110, rachel: 100, barak: 130, jael: 100, josephArimathea: 110, ananias: 100, threeFriends: 150, job: 150, enoch: 110, melchizedek: 120, caleb: 140, jeremiah: 110, ezekiel: 120, ezra: 110, nathan: 110, hezekiah: 120, josiah: 120, magi: 150, shepherds: 140, bartimaeus: 100, centurion: 130, jairus: 110, simonCyrene: 140, thief: 80, jamesJust: 120, mockingThief: 90, jesusCross: 120, widow: 80, fisherman: 100, fourFriends: 160, goodSamaritan: 120, zarephath: 90, shunammite: 100, naaman: 140, maid: 70, bathsheba: 110, mephibosheth: 90, sheba: 110, leah: 110, esau: 140, hagar: 140, lot: 130, jochebed: 100, pharaohDaughter: 100, jethro: 120, zipporah: 100, loisEunice: 130, balaam: 130, pharaoh: 140, charioteer: 110, jezebel: 110, baalProphet: 100, haman: 120, delilah: 100, nebuchadnezzar: 140, ahab: 130, absalom: 120, sapphira: 110, pilate: 130, caiaphas: 120, herod: 120, barabbas: 110, herodias: 110, romanSoldier: 120, romanSpearman: 110, romanArcher: 90, romanCavalry: 130, romanCenturion: 140, sennacherib: 150, belshazzar: 120, korah: 130, achan: 110, sisera: 140, herodGreat: 130, legionFreed: 120, prodigal: 100, ethiopian: 110, johnPatmos: 120, ehud: 120, jephthah: 130, joab: 140, uriah: 140, cyrus: 130, zerubbabel: 130, vashti: 110, michal: 100, gehazi: 100, jehu: 140, simonMagus: 110, herodAgrippa: 130, archerP: 70, bearerP: 110, goliathP: 150, serpentP: 100 };

export const SKILLS: Record<SkillId, SkillDef> = {
  sling: { id: "sling", owner: "david", kind: "attack", cost: 1, damage: 30 },
  slingStone: { id: "slingStone", owner: "david", kind: "faith", cost: 3, damage: 140 },
  rebuke: { id: "rebuke", owner: "samuel", kind: "attack", cost: 1, damage: 20 },
  heal: { id: "heal", owner: "samuel", kind: "guard", cost: 1 },
  arise: { id: "arise", owner: "samuel", kind: "guard", cost: 2 },
  sword: { id: "sword", owner: "jonathan", kind: "attack", cost: 1, damage: 30 },
  covshield: { id: "covshield", owner: "jonathan", kind: "guard", cost: 1 },
  till: { id: "till", owner: "adam", kind: "attack", cost: 1, damage: 30 },
  keep: { id: "keep", owner: "adam", kind: "guard", cost: 1 },
  mother: { id: "mother", owner: "eve", kind: "guard", cost: 1 },
  helper: { id: "helper", owner: "eve", kind: "guard", cost: 1 },
  offering: { id: "offering", owner: "cain", kind: "attack", cost: 1, damage: 20 },
  mark: { id: "mark", owner: "cain", kind: "guard", cost: 2 },
  firstlings: { id: "firstlings", owner: "abel", kind: "guard", cost: 1 },
  faithOffering: { id: "faithOffering", owner: "abel", kind: "attack", cost: 1, damage: 20 },
  ark: { id: "ark", owner: "noah", kind: "guard", cost: 2 },
  rainbow: { id: "rainbow", owner: "noah", kind: "guard", cost: 3 },
  stars: { id: "stars", owner: "abraham", kind: "guard", cost: 1 },
  provide: { id: "provide", owner: "abraham", kind: "faith", cost: 2 },
  harvest: { id: "harvest", owner: "isaac", kind: "attack", cost: 1, damage: 20 },
  ram: { id: "ram", owner: "isaac", kind: "guard", cost: 2 },
  wrestle: { id: "wrestle", owner: "jacob", kind: "attack", cost: 2, damage: 40 },
  ladder: { id: "ladder", owner: "jacob", kind: "faith", cost: 3 },
  granary: { id: "granary", owner: "joseph", kind: "guard", cost: 2 },
  meantForGood: { id: "meantForGood", owner: "joseph", kind: "faith", cost: 2 },
  sea: { id: "sea", owner: "moses", kind: "faith", cost: 3, damage: 60 },
  handsUp: { id: "handsUp", owner: "moses", kind: "guard", cost: 2 },
  blessing: { id: "blessing", owner: "aaron", kind: "guard", cost: 1 },
  breastplate: { id: "breastplate", owner: "aaron", kind: "guard", cost: 2 },
  timbrel: { id: "timbrel", owner: "miriam", kind: "attack", cost: 1, damage: 10 },
  song: { id: "song", owner: "miriam", kind: "guard", cost: 2 },
  tenWords: { id: "tenWords", owner: "mosesSinai", kind: "guard", cost: 2 },
  faceShone: { id: "faceShone", owner: "mosesSinai", kind: "faith", cost: 3 },
  courage: { id: "courage", owner: "joshua", kind: "attack", cost: 1, damage: 30 },
  jericho: { id: "jericho", owner: "joshua", kind: "faith", cost: 3, damage: 40 },
  hideSpies: { id: "hideSpies", owner: "rahab", kind: "guard", cost: 1 },
  scarletCord: { id: "scarletCord", owner: "rahab", kind: "guard", cost: 3 },
  upToday: { id: "upToday", owner: "deborah", kind: "attack", cost: 1 },
  starsFought: { id: "starsFought", owner: "deborah", kind: "faith", cost: 3, damage: 60 },
  fleece: { id: "fleece", owner: "gideon", kind: "guard", cost: 1 },
  torches: { id: "torches", owner: "gideon", kind: "faith", cost: 3, damage: 30 },
  jawbone: { id: "jawbone", owner: "samson", kind: "attack", cost: 2, damage: 30 },
  pillars: { id: "pillars", owner: "samson", kind: "faith", cost: 3, damage: 100 },
  glean: { id: "glean", owner: "ruth", kind: "guard", cost: 1 },
  whither: { id: "whither", owner: "ruth", kind: "guard", cost: 1 },
  counsel: { id: "counsel", owner: "naomi", kind: "guard", cost: 1 },
  restorer: { id: "restorer", owner: "naomi", kind: "guard", cost: 2 },
  wings: { id: "wings", owner: "boaz", kind: "guard", cost: 2 },
  redeemer: { id: "redeemer", owner: "boaz", kind: "guard", cost: 2 },
  prayer: { id: "prayer", owner: "hannah", kind: "guard", cost: 1 },
  hannahSong: { id: "hannahSong", owner: "hannah", kind: "faith", cost: 3, damage: 40 },
  javelin: { id: "javelin", owner: "saul", kind: "attack", cost: 1, damage: 30 },
  rashOffering: { id: "rashOffering", owner: "saul", kind: "guard", cost: 1 },
  provision: { id: "provision", owner: "abigail", kind: "guard", cost: 1 },
  intercede: { id: "intercede", owner: "abigail", kind: "guard", cost: 2 },
  wisdom: { id: "wisdom", owner: "solomon", kind: "guard", cost: 1 },
  templeFire: { id: "templeFire", owner: "solomon", kind: "faith", cost: 3, damage: 50 },
  ravens: { id: "ravens", owner: "elijah", kind: "guard", cost: 1 },
  carmel: { id: "carmel", owner: "elijah", kind: "faith", cost: 3, damage: 80 },
  healWaters: { id: "healWaters", owner: "elisha", kind: "guard", cost: 1 },
  chariots: { id: "chariots", owner: "elisha", kind: "faith", cost: 2 },
  castIntoSea: { id: "castIntoSea", owner: "jonah", kind: "guard", cost: 1 },
  nineveh: { id: "nineveh", owner: "jonah", kind: "attack", cost: 2, damage: 20 },
  sendMe: { id: "sendMe", owner: "isaiah", kind: "attack", cost: 1, damage: 30 },
  greatLight: { id: "greatLight", owner: "isaiah", kind: "faith", cost: 3, damage: 60 },
  fasting: { id: "fasting", owner: "esther", kind: "guard", cost: 1 },
  contrary: { id: "contrary", owner: "esther", kind: "faith", cost: 3 },
  stoneCut: { id: "stoneCut", owner: "daniel", kind: "attack", cost: 2, damage: 50 },
  lionsDen: { id: "lionsDen", owner: "daniel", kind: "faith", cost: 2 },
  buildWall: { id: "buildWall", owner: "nehemiah", kind: "guard", cost: 1 },
  swordAndTrowel: { id: "swordAndTrowel", owner: "nehemiah", kind: "attack", cost: 1, damage: 20 },
  incense: { id: "incense", owner: "zechariah", kind: "guard", cost: 1 },
  nameIsJohn: { id: "nameIsJohn", owner: "zechariah", kind: "guard", cost: 2 },
  handmaid: { id: "handmaid", owner: "mary", kind: "guard", cost: 1 },
  magnificat: { id: "magnificat", owner: "mary", kind: "faith", cost: 3 },
  carpenter: { id: "carpenter", owner: "josephNaz", kind: "guard", cost: 1 },
  dreamWarning: { id: "dreamWarning", owner: "josephNaz", kind: "faith", cost: 2 },
  axe: { id: "axe", owner: "johnBaptist", kind: "attack", cost: 2, damage: 40 },
  baptism: { id: "baptism", owner: "johnBaptist", kind: "guard", cost: 2 },
  peaceBeUnto: { id: "peaceBeUnto", owner: "jesus", kind: "guard", cost: 1 },
  withYouAlway: { id: "withYouAlway", owner: "jesus", kind: "guard", cost: 2 },
  walkOnWater: { id: "walkOnWater", owner: "jesusUR", kind: "faith", cost: 2 },
  loaves: { id: "loaves", owner: "jesusUR", kind: "faith", cost: 3 },
  greatCatch: { id: "greatCatch", owner: "peter", kind: "guard", cost: 1 },
  drawSword: { id: "drawSword", owner: "peter", kind: "attack", cost: 2, damage: 50 },
  comeAndSee: { id: "comeAndSee", owner: "andrew", kind: "guard", cost: 2 },
  aLadHere: { id: "aLadHere", owner: "andrew", kind: "guard", cost: 1 },
  thunder: { id: "thunder", owner: "johnApostle", kind: "attack", cost: 1, damage: 30 },
  loveOneAnother: { id: "loveOneAnother", owner: "johnApostle", kind: "guard", cost: 2 },
  taxBooth: { id: "taxBooth", owner: "matthew", kind: "guard", cost: 1 },
  feast: { id: "feast", owner: "matthew", kind: "guard", cost: 2 },
  mendNets: { id: "mendNets", owner: "jamesZeb", kind: "guard", cost: 1 },
  boanerges: { id: "boanerges", owner: "jamesZeb", kind: "attack", cost: 1, damage: 30 },
  reachFinger: { id: "reachFinger", owner: "thomas", kind: "guard", cost: 1 },
  myLord: { id: "myLord", owner: "thomas", kind: "faith", cost: 2, damage: 50 },
  spices: { id: "spices", owner: "maryMagdalene", kind: "guard", cost: 1 },
  seenTheLord: { id: "seenTheLord", owner: "maryMagdalene", kind: "faith", cost: 2 },
  serving: { id: "serving", owner: "martha", kind: "attack", cost: 1 },
  riseAgain: { id: "riseAgain", owner: "martha", kind: "faith", cost: 2 },
  sycamore: { id: "sycamore", owner: "zacchaeus", kind: "guard", cost: 1 },
  fourfold: { id: "fourfold", owner: "zacchaeus", kind: "guard", cost: 1 },
  atHisFeet: { id: "atHisFeet", owner: "maryBethany", kind: "guard", cost: 1 },
  spikenard: { id: "spikenard", owner: "maryBethany", kind: "faith", cost: 2 },
  looseHim: { id: "looseHim", owner: "lazarus", kind: "guard", cost: 1 },
  manyBelieved: { id: "manyBelieved", owner: "lazarus", kind: "guard", cost: 1 },
  gracePower: { id: "gracePower", owner: "stephen", kind: "attack", cost: 1, damage: 30 },
  heavensOpened: { id: "heavensOpened", owner: "stephen", kind: "faith", cost: 2 },
  hereIsWater: { id: "hereIsWater", owner: "philip", kind: "guard", cost: 1 },
  samaria: { id: "samaria", owner: "philip", kind: "attack", cost: 2, damage: 20 },
  armourOfGod: { id: "armourOfGod", owner: "paul", kind: "guard", cost: 2 },
  swordOfSpirit: { id: "swordOfSpirit", owner: "paul", kind: "attack", cost: 2, damage: 50 },
  encourage: { id: "encourage", owner: "barnabas", kind: "guard", cost: 1 },
  soldField: { id: "soldField", owner: "barnabas", kind: "guard", cost: 1 },
  midnightHymns: { id: "midnightHymns", owner: "silas", kind: "guard", cost: 1 },
  prisonOpened: { id: "prisonOpened", owner: "silas", kind: "faith", cost: 2, damage: 30 },
  example: { id: "example", owner: "timothy", kind: "guard", cost: 1 },
  stirUpGift: { id: "stirUpGift", owner: "timothy", kind: "attack", cost: 1, damage: 30 },
  purpleCloth: { id: "purpleCloth", owner: "lydia", kind: "guard", cost: 1 },
  abideHouse: { id: "abideHouse", owner: "lydia", kind: "guard", cost: 2 },
  tentmaking: { id: "tentmaking", owner: "priscilla", kind: "guard", cost: 1 },
  expound: { id: "expound", owner: "priscilla", kind: "guard", cost: 1 },
  goInPeace: { id: "goInPeace", owner: "eli", kind: "guard", cost: 1 },
  speakLord: { id: "speakLord", owner: "eli", kind: "guard", cost: 2 },
  tentRope: { id: "tentRope", owner: "aquila", kind: "attack", cost: 1, damage: 20 },
  layDownNeck: { id: "layDownNeck", owner: "aquila", kind: "guard", cost: 1 },
  garments: { id: "garments", owner: "dorcas", kind: "guard", cost: 1 },
  almsdeeds: { id: "almsdeeds", owner: "dorcas", kind: "guard", cost: 1 },
  centurionCommand: { id: "centurionCommand", owner: "cornelius", kind: "attack", cost: 2, damage: 40 },
  prayersAlms: { id: "prayersAlms", owner: "cornelius", kind: "guard", cost: 1 },
  mightyScriptures: { id: "mightyScriptures", owner: "apollos", kind: "attack", cost: 1, damage: 30 },
  watered: { id: "watered", owner: "apollos", kind: "guard", cost: 1 },
  succourer: { id: "succourer", owner: "phoebe", kind: "guard", cost: 1 },
  bearLetter: { id: "bearLetter", owner: "phoebe", kind: "guard", cost: 1 },
  physician: { id: "physician", owner: "luke", kind: "guard", cost: 1 },
  inOrder: { id: "inOrder", owner: "luke", kind: "guard", cost: 1 },
  departed: { id: "departed", owner: "johnMark", kind: "guard", cost: 1 },
  profitable: { id: "profitable", owner: "johnMark", kind: "attack", cost: 1, damage: 20 },
  setInOrder: { id: "setInOrder", owner: "titus", kind: "faith", cost: 1 },
  earnestCare: { id: "earnestCare", owner: "titus", kind: "guard", cost: 2 },
  refreshed: { id: "refreshed", owner: "philemon", kind: "guard", cost: 1 },
  receiveHim: { id: "receiveHim", owner: "philemon", kind: "guard", cost: 2 },
  nowProfitable: { id: "nowProfitable", owner: "onesimus", kind: "attack", cost: 1, damage: 20 },
  belovedBrother: { id: "belovedBrother", owner: "onesimus", kind: "guard", cost: 1 },
  byNight: { id: "byNight", owner: "nicodemus", kind: "guard", cost: 1 },
  bornAgain: { id: "bornAgain", owner: "nicodemus", kind: "faith", cost: 2 },
  livingWater: { id: "livingWater", owner: "samaritan", kind: "guard", cost: 1 },
  comeSee: { id: "comeSee", owner: "samaritan", kind: "guard", cost: 1 },
  waiting: { id: "waiting", owner: "simeon", kind: "guard", cost: 1 },
  nuncDimittis: { id: "nuncDimittis", owner: "simeon", kind: "faith", cost: 2 },
  nightAndDay: { id: "nightAndDay", owner: "anna", kind: "guard", cost: 1 },
  gaveThanks: { id: "gaveThanks", owner: "anna", kind: "guard", cost: 1 },
  giveBasket: { id: "giveBasket", owner: "loavesBoy", kind: "guard", cost: 1 },
  pebble: { id: "pebble", owner: "loavesBoy", kind: "attack", cost: 1, damage: 10 },
  thirtySilver: { id: "thirtySilver", owner: "judas", kind: "guard", cost: 1 },
  moneyBag: { id: "moneyBag", owner: "judas", kind: "attack", cost: 1, damage: 20 },
  philipComeSee: { id: "philipComeSee", owner: "philipApostle", kind: "guard", cost: 1 },
  twoHundredPence: { id: "twoHundredPence", owner: "philipApostle", kind: "attack", cost: 1, damage: 30 },
  figTree: { id: "figTree", owner: "nathanael", kind: "guard", cost: 1 },
  noGuile: { id: "noGuile", owner: "nathanael", kind: "attack", cost: 1, damage: 30 },
  quietFaith: { id: "quietFaith", owner: "jamesAlph", kind: "guard", cost: 1 },
  oneOfTwelve: { id: "oneOfTwelve", owner: "jamesAlph", kind: "attack", cost: 1, damage: 20 },
  aQuestion: { id: "aQuestion", owner: "thaddaeus", kind: "guard", cost: 1 },
  contendFaith: { id: "contendFaith", owner: "thaddaeus", kind: "attack", cost: 1, damage: 30 },
  zeal: { id: "zeal", owner: "simonZealot", kind: "attack", cost: 1, damage: 30 },
  swordDown: { id: "swordDown", owner: "simonZealot", kind: "guard", cost: 1 },
  lotFell: { id: "lotFell", owner: "matthias", kind: "guard", cost: 1 },
  withEleven: { id: "withEleven", owner: "matthias", kind: "attack", cost: 1, damage: 20 },
  leaped: { id: "leaped", owner: "elizabeth", kind: "guard", cost: 1 },
  blessedAmong: { id: "blessedAmong", owner: "elizabeth", kind: "faith", cost: 2 },
  wouldNotBow: { id: "wouldNotBow", owner: "mordecai", kind: "guard", cost: 1 },
  suchATime: { id: "suchATime", owner: "mordecai", kind: "guard", cost: 1 },
  laughter: { id: "laughter", owner: "sarah", kind: "guard", cost: 1 },
  tooHard: { id: "tooHard", owner: "sarah", kind: "faith", cost: 2 },
  drinkMyLord: { id: "drinkMyLord", owner: "rebekah", kind: "guard", cost: 1 },
  waterCamels: { id: "waterCamels", owner: "rebekah", kind: "guard", cost: 2 },
  keepSheep: { id: "keepSheep", owner: "rachel", kind: "guard", cost: 1 },
  fewDays: { id: "fewDays", owner: "rachel", kind: "guard", cost: 1 },
  ifThouGo: { id: "ifThouGo", owner: "barak", kind: "guard", cost: 1 },
  downTabor: { id: "downTabor", owner: "barak", kind: "attack", cost: 1, damage: 30 },
  blessedAbove: { id: "blessedAbove", owner: "jael", kind: "guard", cost: 1 },
  tentPeg: { id: "tentPeg", owner: "jael", kind: "attack", cost: 2, damage: 40 },
  wentInBoldly: { id: "wentInBoldly", owner: "josephArimathea", kind: "guard", cost: 1 },
  fineLinen: { id: "fineLinen", owner: "josephArimathea", kind: "guard", cost: 1 },
  brotherSaul: { id: "brotherSaul", owner: "ananias", kind: "guard", cost: 1 },
  scalesFell: { id: "scalesFell", owner: "ananias", kind: "guard", cost: 1 },
  butIfNot: { id: "butIfNot", owner: "threeFriends", kind: "guard", cost: 1 },
  fourthMan: { id: "fourthMan", owner: "threeFriends", kind: "faith", cost: 3 },
  lordGave: { id: "lordGave", owner: "job", kind: "guard", cost: 1 },
  turnedCaptivity: { id: "turnedCaptivity", owner: "job", kind: "faith", cost: 2 },
  walkedWithGod: { id: "walkedWithGod", owner: "enoch", kind: "guard", cost: 1 },
  saintsCome: { id: "saintsCome", owner: "enoch", kind: "attack", cost: 2, damage: 40 },
  breadAndWine: { id: "breadAndWine", owner: "melchizedek", kind: "guard", cost: 1 },
  tenthOfAll: { id: "tenthOfAll", owner: "melchizedek", kind: "guard", cost: 2 },
  goUpAtOnce: { id: "goUpAtOnce", owner: "caleb", kind: "guard", cost: 1 },
  thisMountain: { id: "thisMountain", owner: "caleb", kind: "attack", cost: 2, damage: 40 },
  almondRod: { id: "almondRod", owner: "jeremiah", kind: "guard", cost: 1 },
  fireInBones: { id: "fireInBones", owner: "jeremiah", kind: "attack", cost: 1, damage: 30 },
  watchman: { id: "watchman", owner: "ezekiel", kind: "guard", cost: 1 },
  dryBones: { id: "dryBones", owner: "ezekiel", kind: "faith", cost: 3 },
  preparedHeart: { id: "preparedHeart", owner: "ezra", kind: "guard", cost: 1 },
  readTheLaw: { id: "readTheLaw", owner: "ezra", kind: "guard", cost: 2 },
  thouArtTheMan: { id: "thouArtTheMan", owner: "nathan", kind: "attack", cost: 1, damage: 30 },
  houseForever: { id: "houseForever", owner: "nathan", kind: "guard", cost: 1 },
  spreadLetter: { id: "spreadLetter", owner: "hezekiah", kind: "faith", cost: 3, damage: 50 },
  fifteenYears: { id: "fifteenYears", owner: "hezekiah", kind: "guard", cost: 1 },
  heardTheBook: { id: "heardTheBook", owner: "josiah", kind: "guard", cost: 1 },
  purgeIdols: { id: "purgeIdols", owner: "josiah", kind: "attack", cost: 2, damage: 40 },
  hisStar: { id: "hisStar", owner: "magi", kind: "guard", cost: 1 },
  threeGifts: { id: "threeGifts", owner: "magi", kind: "faith", cost: 3 },
  goodTidings: { id: "goodTidings", owner: "shepherds", kind: "guard", cost: 1 },
  gloryHighest: { id: "gloryHighest", owner: "shepherds", kind: "faith", cost: 2 },
  sonOfDavid: { id: "sonOfDavid", owner: "bartimaeus", kind: "guard", cost: 1 },
  castGarment: { id: "castGarment", owner: "bartimaeus", kind: "attack", cost: 1, damage: 30 },
  speakTheWord: { id: "speakTheWord", owner: "centurion", kind: "guard", cost: 2 },
  underAuthority: { id: "underAuthority", owner: "centurion", kind: "faith", cost: 2 },
  onlyBelieve: { id: "onlyBelieve", owner: "jairus", kind: "guard", cost: 1 },
  talithaCumi: { id: "talithaCumi", owner: "jairus", kind: "faith", cost: 2 },
  bearHisCross: { id: "bearHisCross", owner: "simonCyrene", kind: "guard", cost: 1 },
  comingFromCountry: { id: "comingFromCountry", owner: "simonCyrene", kind: "guard", cost: 1 },
  rememberMe: { id: "rememberMe", owner: "thief", kind: "guard", cost: 1 },
  paradise: { id: "paradise", owner: "thief", kind: "faith", cost: 1 },
  swiftToHear: { id: "swiftToHear", owner: "jamesJust", kind: "guard", cost: 1 },
  faithWorks: { id: "faithWorks", owner: "jamesJust", kind: "attack", cost: 1, damage: 20 },
  saveThyself: { id: "saveThyself", owner: "mockingThief", kind: "attack", cost: 1, damage: 30 },
  railedOn: { id: "railedOn", owner: "mockingThief", kind: "attack", cost: 2, damage: 50 },
  forgiveThem: { id: "forgiveThem", owner: "jesusCross", kind: "guard", cost: 1 },
  commitSpirit: { id: "commitSpirit", owner: "jesusCross", kind: "faith", cost: 3, damage: 60 },
  twoMites: { id: "twoMites", owner: "widow", kind: "guard", cost: 1 },
  allHerLiving: { id: "allHerLiving", owner: "widow", kind: "guard", cost: 1 },
  toiledAllNight: { id: "toiledAllNight", owner: "fisherman", kind: "guard", cost: 1 },
  atThyWord: { id: "atThyWord", owner: "fisherman", kind: "attack", cost: 1, damage: 20 },
  throughTheRoof: { id: "throughTheRoof", owner: "fourFriends", kind: "guard", cost: 1 },
  theirFaith: { id: "theirFaith", owner: "fourFriends", kind: "guard", cost: 2 },
  oilAndWine: { id: "oilAndWine", owner: "goodSamaritan", kind: "guard", cost: 1 },
  twoPence: { id: "twoPence", owner: "goodSamaritan", kind: "guard", cost: 1 },
  hardenedHeart: { id: "hardenedHeart", owner: "pharaoh", kind: "guard", cost: 1 },
  makeBricks: { id: "makeBricks", owner: "pharaoh", kind: "guard", cost: 1 },
  pursued: { id: "pursued", owner: "charioteer", kind: "attack", cost: 1, damage: 30 },
  chosenChariots: { id: "chosenChariots", owner: "charioteer", kind: "guard", cost: 1 },
  royalCommand: { id: "royalCommand", owner: "jezebel", kind: "guard", cost: 1 },
  sealedLetters: { id: "sealedLetters", owner: "jezebel", kind: "attack", cost: 2, damage: 40 },
  callOnBaal: { id: "callOnBaal", owner: "baalProphet", kind: "attack", cost: 1, damage: 20 },
  cutThemselves: { id: "cutThemselves", owner: "baalProphet", kind: "guard", cost: 1 },
  kingsRing: { id: "kingsRing", owner: "haman", kind: "guard", cost: 1 },
  hamansDecree: { id: "hamansDecree", owner: "haman", kind: "attack", cost: 2, damage: 30 },
  pieceOfSilver: { id: "pieceOfSilver", owner: "delilah", kind: "guard", cost: 1 },
  whereinStrength: { id: "whereinStrength", owner: "delilah", kind: "attack", cost: 2, damage: 40 },
  sevenTimesHotter: { id: "sevenTimesHotter", owner: "nebuchadnezzar", kind: "attack", cost: 2, damage: 30 },
  praiseKingOfHeaven: { id: "praiseKingOfHeaven", owner: "nebuchadnezzar", kind: "faith", cost: 2 },
  covetVineyard: { id: "covetVineyard", owner: "ahab", kind: "guard", cost: 1 },
  humbledHimself: { id: "humbledHimself", owner: "ahab", kind: "faith", cost: 2 },
  stoleHearts: { id: "stoleHearts", owner: "absalom", kind: "guard", cost: 1 },
  fiftyMen: { id: "fiftyMen", owner: "absalom", kind: "attack", cost: 2, damage: 40 },
  soldPossession: { id: "soldPossession", owner: "sapphira", kind: "guard", cost: 1 },
  keptBackPart: { id: "keptBackPart", owner: "sapphira", kind: "guard", cost: 1 },
  noFault: { id: "noFault", owner: "pilate", kind: "guard", cost: 1 },
  washedHands: { id: "washedHands", owner: "pilate", kind: "guard", cost: 1 },
  oneManDie: { id: "oneManDie", owner: "caiaphas", kind: "guard", cost: 1 },
  rentClothes: { id: "rentClothes", owner: "caiaphas", kind: "attack", cost: 2, damage: 40 },
  hopedSign: { id: "hopedSign", owner: "herod", kind: "guard", cost: 1 },
  gorgeousRobe: { id: "gorgeousRobe", owner: "herod", kind: "guard", cost: 1 },
  insurrection: { id: "insurrection", owner: "barabbas", kind: "attack", cost: 1, damage: 30 },
  releasedUnto: { id: "releasedUnto", owner: "barabbas", kind: "guard", cost: 1 },
  convenientDay: { id: "convenientDay", owner: "herodias", kind: "guard", cost: 1 },
  heldGrudge: { id: "heldGrudge", owner: "herodias", kind: "attack", cost: 2, damage: 40 },
  shieldWall: { id: "shieldWall", owner: "romanSoldier", kind: "guard", cost: 1 },
  gladius: { id: "gladius", owner: "romanSoldier", kind: "attack", cost: 1, damage: 30 },
  braceSpears: { id: "braceSpears", owner: "romanSpearman", kind: "guard", cost: 1 },
  pilum: { id: "pilum", owner: "romanSpearman", kind: "attack", cost: 1, damage: 20 },
  aimedShot: { id: "aimedShot", owner: "romanArcher", kind: "attack", cost: 1, damage: 30 },
  arrowVolley: { id: "arrowVolley", owner: "romanArcher", kind: "attack", cost: 2, damage: 20 },
  rideOut: { id: "rideOut", owner: "romanCavalry", kind: "guard", cost: 1 },
  cavalryCharge: { id: "cavalryCharge", owner: "romanCavalry", kind: "attack", cost: 2, damage: 40 },
  commandCohort: { id: "commandCohort", owner: "romanCenturion", kind: "guard", cost: 1 },
  trulySonOfGod: { id: "trulySonOfGod", owner: "romanCenturion", kind: "guard", cost: 2 },
  whomTrust: { id: "whomTrust", owner: "sennacherib", kind: "guard", cost: 1 },
  fencedCities: { id: "fencedCities", owner: "sennacherib", kind: "attack", cost: 2, damage: 30 },
  goldenVessels: { id: "goldenVessels", owner: "belshazzar", kind: "guard", cost: 1 },
  writingOnWall: { id: "writingOnWall", owner: "belshazzar", kind: "guard", cost: 1 },
  takeTooMuch: { id: "takeTooMuch", owner: "korah", kind: "guard", cost: 1 },
  strangeCensers: { id: "strangeCensers", owner: "korah", kind: "attack", cost: 2, damage: 40 },
  hiddenSpoil: { id: "hiddenSpoil", owner: "achan", kind: "guard", cost: 1 },
  troubleOfAchor: { id: "troubleOfAchor", owner: "achan", kind: "attack", cost: 2, damage: 30 },
  ironChariots: { id: "ironChariots", owner: "sisera", kind: "attack", cost: 2, damage: 25 },
  fledToTent: { id: "fledToTent", owner: "sisera", kind: "guard", cost: 1 },
  privilyCalled: { id: "privilyCalled", owner: "herodGreat", kind: "guard", cost: 1 },
  exceedingWroth: { id: "exceedingWroth", owner: "herodGreat", kind: "attack", cost: 2, damage: 45 },
  rightMind: { id: "rightMind", owner: "legionFreed", kind: "guard", cost: 1 },
  tellHowGreat: { id: "tellHowGreat", owner: "legionFreed", kind: "faith", cost: 2 },
  cameToHimself: { id: "cameToHimself", owner: "prodigal", kind: "guard", cost: 1 },
  bestRobe: { id: "bestRobe", owner: "prodigal", kind: "faith", cost: 2 },
  readingIsaiah: { id: "readingIsaiah", owner: "ethiopian", kind: "guard", cost: 1 },
  wentRejoicing: { id: "wentRejoicing", owner: "ethiopian", kind: "faith", cost: 2 },
  inTheSpirit: { id: "inTheSpirit", owner: "johnPatmos", kind: "guard", cost: 1 },
  newHeaven: { id: "newHeaven", owner: "johnPatmos", kind: "faith", cost: 3 },
  leftHanded: { id: "leftHanded", owner: "ehud", kind: "attack", cost: 1, damage: 30 },
  blewTrumpet: { id: "blewTrumpet", owner: "ehud", kind: "guard", cost: 1 },
  judgeThisDay: { id: "judgeThisDay", owner: "jephthah", kind: "guard", cost: 1 },
  rashVow: { id: "rashVow", owner: "jephthah", kind: "attack", cost: 2, damage: 60 },
  playTheMen: { id: "playTheMen", owner: "joab", kind: "guard", cost: 1 },
  threeDarts: { id: "threeDarts", owner: "joab", kind: "attack", cost: 2, damage: 45 },
  wouldNotGoHome: { id: "wouldNotGoHome", owner: "uriah", kind: "guard", cost: 1 },
  hottestBattle: { id: "hottestBattle", owner: "uriah", kind: "attack", cost: 1, damage: 40 },
  sorceries: { id: "sorceries", owner: "simonMagus", kind: "guard", cost: 1 },
  offeredMoney: { id: "offeredMoney", owner: "simonMagus", kind: "guard", cost: 1 },
  pleasedJews: { id: "pleasedJews", owner: "herodAgrippa", kind: "guard", cost: 1 },
  voiceOfGod: { id: "voiceOfGod", owner: "herodAgrippa", kind: "attack", cost: 2, damage: 30 },
  cyrusDecree: { id: "cyrusDecree", owner: "cyrus", kind: "guard", cost: 1 },
  returnVessels: { id: "returnVessels", owner: "cyrus", kind: "faith", cost: 2 },
  laidFoundation: { id: "laidFoundation", owner: "zerubbabel", kind: "guard", cost: 1 },
  notByMight: { id: "notByMight", owner: "zerubbabel", kind: "faith", cost: 3, damage: 35 },
  refusedToCome: { id: "refusedToCome", owner: "vashti", kind: "guard", cost: 1 },
  royalFeast: { id: "royalFeast", owner: "vashti", kind: "faith", cost: 2 },
  letDownWindow: { id: "letDownWindow", owner: "michal", kind: "guard", cost: 1 },
  imageInBed: { id: "imageInBed", owner: "michal", kind: "guard", cost: 1 },
  ranAfterNaaman: { id: "ranAfterNaaman", owner: "gehazi", kind: "guard", cost: 1 },
  twoTalents: { id: "twoTalents", owner: "gehazi", kind: "guard", cost: 1 },
  drivethFuriously: { id: "drivethFuriously", owner: "jehu", kind: "attack", cost: 2, damage: 45 },
  zealForLord: { id: "zealForLord", owner: "jehu", kind: "guard", cost: 1 },
  mealNotSpent: { id: "mealNotSpent", owner: "zarephath", kind: "guard", cost: 1 },
  littleCake: { id: "littleCake", owner: "zarephath", kind: "guard", cost: 1 },
  littleChamber: { id: "littleChamber", owner: "shunammite", kind: "guard", cost: 1 },
  itIsWell: { id: "itIsWell", owner: "shunammite", kind: "faith", cost: 2 },
  sevenTimesJordan: { id: "sevenTimesJordan", owner: "naaman", kind: "guard", cost: 2 },
  captainOfHost: { id: "captainOfHost", owner: "naaman", kind: "attack", cost: 2, damage: 50 },
  wouldGod: { id: "wouldGod", owner: "maid", kind: "guard", cost: 1 },
  littleMaid: { id: "littleMaid", owner: "maid", kind: "guard", cost: 1 },
  rememberOath: { id: "rememberOath", owner: "bathsheba", kind: "guard", cost: 1 },
  kingsMother: { id: "kingsMother", owner: "bathsheba", kind: "faith", cost: 2 },
  kingsTable: { id: "kingsTable", owner: "mephibosheth", kind: "guard", cost: 1 },
  deadDog: { id: "deadDog", owner: "mephibosheth", kind: "guard", cost: 1 },
  hardQuestions: { id: "hardQuestions", owner: "sheba", kind: "guard", cost: 1 },
  spicesAndGold: { id: "spicesAndGold", owner: "sheba", kind: "faith", cost: 2 },
  lookedUpon: { id: "lookedUpon", owner: "leah", kind: "guard", cost: 1 },
  nowPraise: { id: "nowPraise", owner: "leah", kind: "guard", cost: 2 },
  cunningHunter: { id: "cunningHunter", owner: "esau", kind: "attack", cost: 1, damage: 30 },
  ranToMeet: { id: "ranToMeet", owner: "esau", kind: "guard", cost: 1 },
  godHeard: { id: "godHeard", owner: "hagar", kind: "guard", cost: 1 },
  wellOpened: { id: "wellOpened", owner: "hagar", kind: "faith", cost: 2 },
  escapeForLife: { id: "escapeForLife", owner: "lot", kind: "guard", cost: 1 },
  lookedBack: { id: "lookedBack", owner: "lot", kind: "guard", cost: 1 },
  arkOfBulrushes: { id: "arkOfBulrushes", owner: "jochebed", kind: "guard", cost: 1 },
  nurseHim: { id: "nurseHim", owner: "jochebed", kind: "guard", cost: 1 },
  hadCompassion: { id: "hadCompassion", owner: "pharaohDaughter", kind: "guard", cost: 1 },
  drewHimOut: { id: "drewHimOut", owner: "pharaohDaughter", kind: "guard", cost: 2 },
  shareBurden: { id: "shareBurden", owner: "jethro", kind: "guard", cost: 1 },
  greaterThanAll: { id: "greaterThanAll", owner: "jethro", kind: "guard", cost: 2 },
  wateredFlock: { id: "wateredFlock", owner: "zipporah", kind: "guard", cost: 1 },
  strangerLand: { id: "strangerLand", owner: "zipporah", kind: "guard", cost: 1 },
  unfeignedFaith: { id: "unfeignedFaith", owner: "loisEunice", kind: "guard", cost: 1 },
  fromAChild: { id: "fromAChild", owner: "loisEunice", kind: "guard", cost: 1 },
  donkeySaw: { id: "donkeySaw", owner: "balaam", kind: "guard", cost: 1 },
  blessNotCurse: { id: "blessNotCurse", owner: "balaam", kind: "faith", cost: 2 },
  volley: { id: "volley", owner: "archerP", kind: "attack", cost: 1, damage: 40 },
  shieldUp: { id: "shieldUp", owner: "bearerP", kind: "guard", cost: 1 },
  bash: { id: "bash", owner: "bearerP", kind: "attack", cost: 1, damage: 20 },
  spearThrust: { id: "spearThrust", owner: "goliathP", kind: "attack", cost: 1, damage: 30 },
  taunt: { id: "taunt", owner: "goliathP", kind: "attack", cost: 2, damage: 10 },
  venom: { id: "venom", owner: "serpentP", kind: "attack", cost: 1, damage: 30 },
  beguile: { id: "beguile", owner: "serpentP", kind: "guard", cost: 3 },
};

export const CHARACTER_SKILLS: Record<CharacterId, SkillId[]> = {
  david: ["sling", "slingStone"],
  samuel: ["rebuke", "heal", "arise"],
  jonathan: ["sword", "covshield"],
  adam: ["till", "keep"],
  cain: ["offering", "mark"],
  abel: ["firstlings", "faithOffering"],
  noah: ["ark", "rainbow"],
  abraham: ["stars", "provide"],
  isaac: ["harvest", "ram"],
  jacob: ["wrestle", "ladder"],
  joseph: ["granary", "meantForGood"],
  moses: ["sea", "handsUp"],
  aaron: ["blessing", "breastplate"],
  miriam: ["timbrel", "song"],
  mosesSinai: ["tenWords", "faceShone"],
  joshua: ["courage", "jericho"],
  rahab: ["hideSpies", "scarletCord"],
  deborah: ["upToday", "starsFought"],
  gideon: ["fleece", "torches"],
  samson: ["jawbone", "pillars"],
  ruth: ["glean", "whither"],
  naomi: ["counsel", "restorer"],
  boaz: ["wings", "redeemer"],
  hannah: ["prayer", "hannahSong"],
  saul: ["javelin", "rashOffering"],
  abigail: ["provision", "intercede"],
  solomon: ["wisdom", "templeFire"],
  elijah: ["ravens", "carmel"],
  elisha: ["healWaters", "chariots"],
  jonah: ["castIntoSea", "nineveh"],
  isaiah: ["sendMe", "greatLight"],
  esther: ["fasting", "contrary"],
  daniel: ["stoneCut", "lionsDen"],
  nehemiah: ["buildWall", "swordAndTrowel"],
  zechariah: ["incense", "nameIsJohn"],
  mary: ["handmaid", "magnificat"],
  josephNaz: ["carpenter", "dreamWarning"],
  johnBaptist: ["axe", "baptism"],
  jesus: ["peaceBeUnto", "withYouAlway"],
  jesusUR: ["walkOnWater", "loaves"],
  peter: ["greatCatch", "drawSword"],
  andrew: ["comeAndSee", "aLadHere"],
  johnApostle: ["thunder", "loveOneAnother"],
  matthew: ["taxBooth", "feast"],
  jamesZeb: ["mendNets", "boanerges"],
  thomas: ["reachFinger", "myLord"],
  maryMagdalene: ["spices", "seenTheLord"],
  martha: ["serving", "riseAgain"],
  zacchaeus: ["sycamore", "fourfold"],
  maryBethany: ["atHisFeet", "spikenard"],
  lazarus: ["looseHim", "manyBelieved"],
  stephen: ["gracePower", "heavensOpened"],
  philip: ["hereIsWater", "samaria"],
  paul: ["armourOfGod", "swordOfSpirit"],
  barnabas: ["encourage", "soldField"],
  silas: ["midnightHymns", "prisonOpened"],
  timothy: ["example", "stirUpGift"],
  lydia: ["purpleCloth", "abideHouse"],
  priscilla: ["tentmaking", "expound"],
  eli: ["goInPeace", "speakLord"],
  aquila: ["tentRope", "layDownNeck"],
  dorcas: ["garments", "almsdeeds"],
  cornelius: ["centurionCommand", "prayersAlms"],
  apollos: ["mightyScriptures", "watered"],
  phoebe: ["succourer", "bearLetter"],
  luke: ["physician", "inOrder"],
  johnMark: ["departed", "profitable"],
  titus: ["setInOrder", "earnestCare"],
  philemon: ["refreshed", "receiveHim"],
  onesimus: ["nowProfitable", "belovedBrother"],
  nicodemus: ["byNight", "bornAgain"],
  samaritan: ["livingWater", "comeSee"],
  simeon: ["waiting", "nuncDimittis"],
  anna: ["nightAndDay", "gaveThanks"],
  loavesBoy: ["giveBasket", "pebble"],
  judas: ["thirtySilver", "moneyBag"],
  philipApostle: ["philipComeSee", "twoHundredPence"],
  nathanael: ["figTree", "noGuile"],
  jamesAlph: ["quietFaith", "oneOfTwelve"],
  thaddaeus: ["aQuestion", "contendFaith"],
  simonZealot: ["zeal", "swordDown"],
  matthias: ["lotFell", "withEleven"],
  elizabeth: ["leaped", "blessedAmong"],
  mordecai: ["wouldNotBow", "suchATime"],
  sarah: ["laughter", "tooHard"],
  rebekah: ["drinkMyLord", "waterCamels"],
  rachel: ["keepSheep", "fewDays"],
  barak: ["ifThouGo", "downTabor"],
  jael: ["blessedAbove", "tentPeg"],
  josephArimathea: ["wentInBoldly", "fineLinen"],
  ananias: ["brotherSaul", "scalesFell"],
  threeFriends: ["butIfNot", "fourthMan"],
  job: ["lordGave", "turnedCaptivity"],
  enoch: ["walkedWithGod", "saintsCome"],
  melchizedek: ["breadAndWine", "tenthOfAll"],
  caleb: ["goUpAtOnce", "thisMountain"],
  jeremiah: ["almondRod", "fireInBones"],
  ezekiel: ["watchman", "dryBones"],
  ezra: ["preparedHeart", "readTheLaw"],
  nathan: ["thouArtTheMan", "houseForever"],
  hezekiah: ["spreadLetter", "fifteenYears"],
  josiah: ["heardTheBook", "purgeIdols"],
  magi: ["hisStar", "threeGifts"],
  shepherds: ["goodTidings", "gloryHighest"],
  bartimaeus: ["sonOfDavid", "castGarment"],
  centurion: ["speakTheWord", "underAuthority"],
  jairus: ["onlyBelieve", "talithaCumi"],
  simonCyrene: ["bearHisCross", "comingFromCountry"],
  thief: ["rememberMe", "paradise"],
  jamesJust: ["swiftToHear", "faithWorks"],
  mockingThief: ["saveThyself", "railedOn"],
  jesusCross: ["forgiveThem", "commitSpirit"],
  widow: ["twoMites", "allHerLiving"],
  fisherman: ["toiledAllNight", "atThyWord"],
  fourFriends: ["throughTheRoof", "theirFaith"],
  goodSamaritan: ["oilAndWine", "twoPence"],
  pharaoh: ["hardenedHeart", "makeBricks"],
  charioteer: ["chosenChariots", "pursued"],
  jezebel: ["royalCommand", "sealedLetters"],
  baalProphet: ["cutThemselves", "callOnBaal"],
  haman: ["kingsRing", "hamansDecree"],
  delilah: ["pieceOfSilver", "whereinStrength"],
  nebuchadnezzar: ["sevenTimesHotter", "praiseKingOfHeaven"],
  ahab: ["covetVineyard", "humbledHimself"],
  absalom: ["stoleHearts", "fiftyMen"],
  sapphira: ["soldPossession", "keptBackPart"],
  pilate: ["noFault", "washedHands"],
  caiaphas: ["oneManDie", "rentClothes"],
  herod: ["hopedSign", "gorgeousRobe"],
  barabbas: ["insurrection", "releasedUnto"],
  herodias: ["convenientDay", "heldGrudge"],
  romanSoldier: ["shieldWall", "gladius"],
  romanSpearman: ["braceSpears", "pilum"],
  romanArcher: ["aimedShot", "arrowVolley"],
  romanCavalry: ["rideOut", "cavalryCharge"],
  romanCenturion: ["commandCohort", "trulySonOfGod"],
  sennacherib: ["whomTrust", "fencedCities"],
  belshazzar: ["goldenVessels", "writingOnWall"],
  korah: ["takeTooMuch", "strangeCensers"],
  achan: ["hiddenSpoil", "troubleOfAchor"],
  sisera: ["ironChariots", "fledToTent"],
  herodGreat: ["privilyCalled", "exceedingWroth"],
  legionFreed: ["rightMind", "tellHowGreat"],
  prodigal: ["cameToHimself", "bestRobe"],
  ethiopian: ["readingIsaiah", "wentRejoicing"],
  johnPatmos: ["inTheSpirit", "newHeaven"],
  ehud: ["leftHanded", "blewTrumpet"],
  jephthah: ["judgeThisDay", "rashVow"],
  joab: ["playTheMen", "threeDarts"],
  uriah: ["wouldNotGoHome", "hottestBattle"],
  simonMagus: ["sorceries", "offeredMoney"],
  herodAgrippa: ["pleasedJews", "voiceOfGod"],
  cyrus: ["cyrusDecree", "returnVessels"],
  zerubbabel: ["laidFoundation", "notByMight"],
  vashti: ["refusedToCome", "royalFeast"],
  michal: ["letDownWindow", "imageInBed"],
  gehazi: ["ranAfterNaaman", "twoTalents"],
  jehu: ["drivethFuriously", "zealForLord"],
  zarephath: ["mealNotSpent", "littleCake"],
  shunammite: ["littleChamber", "itIsWell"],
  naaman: ["captainOfHost", "sevenTimesJordan"],
  maid: ["wouldGod", "littleMaid"],
  bathsheba: ["rememberOath", "kingsMother"],
  mephibosheth: ["kingsTable", "deadDog"],
  sheba: ["hardQuestions", "spicesAndGold"],
  leah: ["lookedUpon", "nowPraise"],
  esau: ["cunningHunter", "ranToMeet"],
  hagar: ["godHeard", "wellOpened"],
  lot: ["escapeForLife", "lookedBack"],
  jochebed: ["arkOfBulrushes", "nurseHim"],
  pharaohDaughter: ["hadCompassion", "drewHimOut"],
  jethro: ["shareBurden", "greaterThanAll"],
  zipporah: ["wateredFlock", "strangerLand"],
  loisEunice: ["unfeignedFaith", "fromAChild"],
  balaam: ["donkeySaw", "blessNotCurse"],
  eve: ["mother", "helper"],
  archerP: ["volley"],
  bearerP: ["shieldUp", "bash"],
  goliathP: ["spearThrust", "taunt"],
  serpentP: ["venom", "beguile"],
};

export const CARDS_V2: Record<CardId, CardDef> = {
  delivered: { id: "delivered", energy: "faith" },
  battle: { id: "battle", energy: "faith" },
  trust: { id: "trust", energy: "faith" },
  assurance: { id: "assurance", energy: "faith" },
  inname: { id: "inname", energy: "attack" },
  trains: { id: "trains", energy: "attack" },
  stones: { id: "stones", energy: "attack" },
  wings: { id: "wings", energy: "guard" },
  shepherd: { id: "shepherd", energy: "guard" },
  renewed: { id: "renewed", energy: "guard" },
  bestrong: { id: "bestrong", energy: "guard" },
  covenant: { id: "covenant", energy: "guard" },
};

/** 15 energy cards: ✨ Faith 4, 🗡️ Attack 6, 🕊️ Guard 5. */
export const DECK_V2: CardId[] = [
  "delivered", "battle", "trust", "assurance",
  "inname", "inname", "trains", "trains", "stones", "stones",
  "wings", "shepherd", "renewed", "bestrong", "covenant",
];

export const PHASE1_CYCLE: GoliathActionId[] = ["defy", "spear", "raise", "crush"];
export const PHASE2_CYCLE: GoliathActionId[] = ["swing", "raise", "crush"];
/** The Serpent keeps one cycle; after shedding its skin (half HP) its fang hits harder. */
export const SERPENT_CYCLE: GoliathActionId[] = ["tempt", "fang", "coil", "fang"];
